init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.0.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
- ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
- ps: Write-Host "Setting version to '$env:TAG_VERSION'"
- ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

image:
- Visual Studio 2017
- Ubuntu

configuration: Release

platform:
- x64

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
  - doc/*
  - README.md
  - .gitignore
  - LICENSE

cache:
- CompilerRuntime\packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'

assembly_info:
  patch: true
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- ps: |
    if ($isLinux) {
      $env:EDITION = "mono"
    } else {
      $env:EDITION = "dotnet"
    }
- nuget restore Phlox.sln

build:
  project: Phlox.sln
  parallel: true
  verbosity: minimal
  publish_nuget: false
  publish_nuget_symbols: false
for:
-
  matrix:
    only:
    - image: Ubuntu
  build_script:
  - msbuild Phlox.sln
  test_script:
  - sh: mono ./NUnit.ConsoleRunner.*/tools/nunit3-console.exe $APPVEYOR_BUILD_FOLDER/phlox/*Test*.dll --result=TEST_RESULTS.xml;format=AppVeyor

after_build:
- ps: Set-Location "$env:APPVEYOR_BUILD_FOLDER"
- ps: Rename-Item -Path bin -NewName phlox
- sh: nuget install NUnit.Runners

test:
  assemblies:
    only:
    - '**/CompilerTests.dll'

on_finish:
- sh: find "$APPVEYOR_BUILD_FOLDER" -type f -name 'TEST*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/nunit/$APPVEYOR_JOB_ID"

artifacts:
- path: phlox
  name: Phlox-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
  type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: DlRS0U90AATbPkzxigCLwaGe1vguHFeC3a0YhMZRA/OYEbLQ8+ybp2OGfqgwpbW4
  artifact: Phlox-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
