using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace InWorldz.Phlox.Compiler
{
    public class DefaultConstants
    {
        static public Dictionary<string, ConstantSymbol> Constants = new Dictionary<string,ConstantSymbol>()
        {
            {"TRUE",    new ConstantSymbol("TRUE", SymbolTable.INT, "1")},
            {"FALSE",   new ConstantSymbol("FALSE", SymbolTable.INT, "0")},

            {"ZERO_VECTOR",         new ConstantSymbol("ZERO_VECTOR", SymbolTable.VECTOR, "<0.0,0.0,0.0>")},
            {"NULL_KEY",            new ConstantSymbol("NULL_KEY", SymbolTable.KEY, "00000000-0000-0000-0000-000000000000")},
            {"ZERO_ROTATION",       new ConstantSymbol("ZERO_ROTATION", SymbolTable.ROTATION, "<0.0,0.0,0.0,1.0>")},

            {"TOUCH_INVALID_TEXCOORD",     new ConstantSymbol("TOUCH_INVALID_TEXCOORD", SymbolTable.VECTOR, "<-1.0,-1.0,0.0>")},
            {"TOUCH_INVALID_VECTOR",       new ConstantSymbol("TOUCH_INVALID_VECTOR", SymbolTable.VECTOR, "<0.0,0.0,0.0>")},
            {"TOUCH_INVALID_FACE",         new ConstantSymbol("TOUCH_INVALID_FACE", SymbolTable.INT, "0x7FFFFFFF")},


            {"PAY_HIDE", new ConstantSymbol("PAY_HIDE", SymbolTable.INT, "-1")},
            {"PAY_DEFAULT", new ConstantSymbol("PAY_DEFAULT", SymbolTable.INT, "-2")},

            {"STATUS_PHYSICS", new ConstantSymbol("STATUS_PHYSICS", SymbolTable.INT, "1")},
            {"STATUS_ROTATE_X", new ConstantSymbol("STATUS_ROTATE_X", SymbolTable.INT, "2")},
            {"STATUS_ROTATE_Y", new ConstantSymbol("STATUS_ROTATE_Y", SymbolTable.INT, "4")},
            {"STATUS_ROTATE_Z", new ConstantSymbol("STATUS_ROTATE_Z", SymbolTable.INT, "8")},
            {"STATUS_PHANTOM", new ConstantSymbol("STATUS_PHANTOM", SymbolTable.INT, "16")},
            {"STATUS_SANDBOX", new ConstantSymbol("STATUS_SANDBOX", SymbolTable.INT, "32")},
            {"STATUS_BLOCK_GRAB", new ConstantSymbol("STATUS_BLOCK_GRAB", SymbolTable.INT, "64")},
            {"STATUS_DIE_AT_EDGE", new ConstantSymbol("STATUS_DIE_AT_EDGE", SymbolTable.INT, "128")},
            {"STATUS_RETURN_AT_EDGE", new ConstantSymbol("STATUS_RETURN_AT_EDGE", SymbolTable.INT, "256")},
            {"STATUS_CAST_SHADOWS", new ConstantSymbol("STATUS_CAST_SHADOWS", SymbolTable.INT, "512")},
            {"STATUS_BLOCK_GRAB_OBJECT", new ConstantSymbol("STATUS_BLOCK_GRAB_OBJECT", SymbolTable.INT, "1024")},
            {"AGENT", new ConstantSymbol("AGENT", SymbolTable.INT, "1")},
            {"ACTIVE", new ConstantSymbol("ACTIVE", SymbolTable.INT, "2")},
            {"PASSIVE", new ConstantSymbol("PASSIVE", SymbolTable.INT, "4")},
            {"SCRIPTED", new ConstantSymbol("SCRIPTED", SymbolTable.INT, "8")},
            {"CONTROL_FWD", new ConstantSymbol("CONTROL_FWD", SymbolTable.INT, "1")},
            {"CONTROL_BACK", new ConstantSymbol("CONTROL_BACK", SymbolTable.INT, "2")},
            {"CONTROL_LEFT", new ConstantSymbol("CONTROL_LEFT", SymbolTable.INT, "4")},
            {"CONTROL_RIGHT", new ConstantSymbol("CONTROL_RIGHT", SymbolTable.INT, "8")},
            {"CONTROL_UP", new ConstantSymbol("CONTROL_UP", SymbolTable.INT, "16")},
            {"CONTROL_DOWN", new ConstantSymbol("CONTROL_DOWN", SymbolTable.INT, "32")},
            {"CONTROL_ROT_LEFT", new ConstantSymbol("CONTROL_ROT_LEFT", SymbolTable.INT, "256")},
            {"CONTROL_ROT_RIGHT", new ConstantSymbol("CONTROL_ROT_RIGHT", SymbolTable.INT, "512")},
            {"CONTROL_LBUTTON", new ConstantSymbol("CONTROL_LBUTTON", SymbolTable.INT, "268435456")},
            {"CONTROL_ML_LBUTTON", new ConstantSymbol("CONTROL_ML_LBUTTON", SymbolTable.INT, "1073741824")},
            {"PERMISSION_DEBIT", new ConstantSymbol("PERMISSION_DEBIT", SymbolTable.INT, "2")},
            {"PERMISSION_TAKE_CONTROLS", new ConstantSymbol("PERMISSION_TAKE_CONTROLS", SymbolTable.INT, "4")},
            {"PERMISSION_REMAP_CONTROLS", new ConstantSymbol("PERMISSION_REMAP_CONTROLS", SymbolTable.INT, "8")},
            {"PERMISSION_TRIGGER_ANIMATION", new ConstantSymbol("PERMISSION_TRIGGER_ANIMATION", SymbolTable.INT, "16")},
            {"PERMISSION_ATTACH", new ConstantSymbol("PERMISSION_ATTACH", SymbolTable.INT, "32")},
            {"PERMISSION_RELEASE_OWNERSHIP", new ConstantSymbol("PERMISSION_RELEASE_OWNERSHIP", SymbolTable.INT, "64")},
            {"PERMISSION_CHANGE_LINKS", new ConstantSymbol("PERMISSION_CHANGE_LINKS", SymbolTable.INT, "128")},
            {"PERMISSION_CHANGE_JOINTS", new ConstantSymbol("PERMISSION_CHANGE_JOINTS", SymbolTable.INT, "256")},
            {"PERMISSION_CHANGE_PERMISSIONS", new ConstantSymbol("PERMISSION_CHANGE_PERMISSIONS", SymbolTable.INT, "512")},
            {"PERMISSION_TRACK_CAMERA", new ConstantSymbol("PERMISSION_TRACK_CAMERA", SymbolTable.INT, "1024")},
            {"PERMISSION_CONTROL_CAMERA", new ConstantSymbol("PERMISSION_CONTROL_CAMERA", SymbolTable.INT, "2048")},
            {"PERMISSION_TELEPORT", new ConstantSymbol("PERMISSION_TELEPORT", SymbolTable.INT, "4096")},
            {"PERMISSION_SILENT_ESTATE_MANAGEMENT", new ConstantSymbol("PERMISSION_SILENT_ESTATE_MANAGEMENT", SymbolTable.INT, "16384")},
            {"PERMISSION_OVERRIDE_ANIMATIONS", new ConstantSymbol("PERMISSION_OVERRIDE_ANIMATIONS", SymbolTable.INT, "32768")},
            {"AGENT_FLYING", new ConstantSymbol("AGENT_FLYING", SymbolTable.INT, "1")},
            {"AGENT_ATTACHMENTS", new ConstantSymbol("AGENT_ATTACHMENTS", SymbolTable.INT, "2")},
            {"AGENT_SCRIPTED", new ConstantSymbol("AGENT_SCRIPTED", SymbolTable.INT, "4")},
            {"AGENT_MOUSELOOK", new ConstantSymbol("AGENT_MOUSELOOK", SymbolTable.INT, "8")},
            {"AGENT_SITTING", new ConstantSymbol("AGENT_SITTING", SymbolTable.INT, "16")},
            {"AGENT_ON_OBJECT", new ConstantSymbol("AGENT_ON_OBJECT", SymbolTable.INT, "32")},
            {"AGENT_AWAY", new ConstantSymbol("AGENT_AWAY", SymbolTable.INT, "64")},
            {"AGENT_WALKING", new ConstantSymbol("AGENT_WALKING", SymbolTable.INT, "128")},
            {"AGENT_IN_AIR", new ConstantSymbol("AGENT_IN_AIR", SymbolTable.INT, "256")},
            {"AGENT_TYPING", new ConstantSymbol("AGENT_TYPING", SymbolTable.INT, "512")},
            {"AGENT_CROUCHING", new ConstantSymbol("AGENT_CROUCHING", SymbolTable.INT, "1024")},
            {"AGENT_BUSY", new ConstantSymbol("AGENT_BUSY", SymbolTable.INT, "2048")},
            {"AGENT_ALWAYS_RUN", new ConstantSymbol("AGENT_ALWAYS_RUN", SymbolTable.INT, "4096")},

			{"PSYS_PART_FLAGS", new ConstantSymbol("PSYS_PART_FLAGS", SymbolTable.INT, "0")},
			{"PSYS_PART_BOUNCE_MASK", new ConstantSymbol("PSYS_PART_BOUNCE_MASK", SymbolTable.INT, "4")},
			{"PSYS_PART_EMISSIVE_MASK", new ConstantSymbol("PSYS_PART_EMISSIVE_MASK", SymbolTable.INT, "256")},
			{"PSYS_PART_FOLLOW_SRC_MASK", new ConstantSymbol("PSYS_PART_FOLLOW_SRC_MASK", SymbolTable.INT, "16")},
			{"PSYS_PART_FOLLOW_VELOCITY_MASK", new ConstantSymbol("PSYS_PART_FOLLOW_VELOCITY_MASK", SymbolTable.INT, "32")},
            {"PSYS_PART_INTERP_COLOR_MASK", new ConstantSymbol("PSYS_PART_INTERP_COLOR_MASK", SymbolTable.INT, "1")},
            {"PSYS_PART_INTERP_SCALE_MASK", new ConstantSymbol("PSYS_PART_INTERP_SCALE_MASK", SymbolTable.INT, "2")},
			{"PSYS_PART_RIBBON_MASK", new ConstantSymbol("PSYS_PART_RIBBON_MASK", SymbolTable.INT, "1024")},
			{"PSYS_PART_TARGET_LINEAR_MASK", new ConstantSymbol("PSYS_PART_TARGET_LINEAR_MASK", SymbolTable.INT, "128")},
			{"PSYS_PART_TARGET_POS_MASK", new ConstantSymbol("PSYS_PART_TARGET_POS_MASK", SymbolTable.INT, "64")},
            {"PSYS_PART_WIND_MASK", new ConstantSymbol("PSYS_PART_WIND_MASK", SymbolTable.INT, "8")},
			{"PSYS_SRC_PATTERN", new ConstantSymbol("PSYS_SRC_PATTERN", SymbolTable.INT, "9")},
			{"PSYS_SRC_PATTERN_EXPLODE", new ConstantSymbol("PSYS_SRC_PATTERN_EXPLODE", SymbolTable.INT, "2")},
			{"PSYS_SRC_PATTERN_ANGLE_CONE", new ConstantSymbol("PSYS_SRC_PATTERN_ANGLE_CONE", SymbolTable.INT, "8")},
			{"PSYS_SRC_PATTERN_ANGLE", new ConstantSymbol("PSYS_SRC_PATTERN_ANGLE", SymbolTable.INT, "4")},
			{"PSYS_SRC_PATTERN_DROP", new ConstantSymbol("PSYS_SRC_PATTERN_DROP", SymbolTable.INT, "1")},
			{"PSYS_SRC_PATTERN_ANGLE_CONE_EMPTY", new ConstantSymbol("PSYS_SRC_PATTERN_ANGLE_CONE_EMPTY", SymbolTable.INT, "16")},
			{"PSYS_SRC_BURST_RADIUS", new ConstantSymbol("PSYS_SRC_BURST_RADIUS", SymbolTable.INT, "16")},
			{"PSYS_SRC_ANGLE_BEGIN", new ConstantSymbol("PSYS_SRC_ANGLE_BEGIN", SymbolTable.INT, "22")},
			{"PSYS_SRC_ANGLE_END", new ConstantSymbol("PSYS_SRC_ANGLE_END", SymbolTable.INT, "23")},
			{"PSYS_SRC_INNERANGLE", new ConstantSymbol("PSYS_SRC_INNERANGLE", SymbolTable.INT, "10")},	// Deprecated: Use PSYS_SRC_ANGLE_BEGIN
			{"PSYS_SRC_OUTERANGLE", new ConstantSymbol("PSYS_SRC_OUTERANGLE", SymbolTable.INT, "11")},	// Deprecated: Use PSYS_SRC_ANGLE_END
			{"PSYS_SRC_TARGET_KEY", new ConstantSymbol("PSYS_SRC_TARGET_KEY", SymbolTable.INT, "20")},
            {"PSYS_PART_START_COLOR", new ConstantSymbol("PSYS_PART_START_COLOR", SymbolTable.INT, "1")},
			{"PSYS_PART_END_COLOR", new ConstantSymbol("PSYS_PART_END_COLOR", SymbolTable.INT, "3")},
            {"PSYS_PART_START_ALPHA", new ConstantSymbol("PSYS_PART_START_ALPHA", SymbolTable.INT, "2")},
            {"PSYS_PART_END_ALPHA", new ConstantSymbol("PSYS_PART_END_ALPHA", SymbolTable.INT, "4")},
            {"PSYS_PART_START_SCALE", new ConstantSymbol("PSYS_PART_START_SCALE", SymbolTable.INT, "5")},
            {"PSYS_PART_END_SCALE", new ConstantSymbol("PSYS_PART_END_SCALE", SymbolTable.INT, "6")},
			{"PSYS_SRC_TEXTURE", new ConstantSymbol("PSYS_SRC_TEXTURE", SymbolTable.INT, "12")},
			{"PSYS_PART_START_GLOW", new ConstantSymbol("PSYS_PART_START_GLOW", SymbolTable.INT, "26")},
			{"PSYS_PART_END_GLOW", new ConstantSymbol("PSYS_PART_END_GLOW", SymbolTable.INT, "27")},
			{"PSYS_PART_BLEND_FUNC_SOURCE", new ConstantSymbol("PSYS_PART_BLEND_FUNC_SOURCE", SymbolTable.INT, "24")},
			{"PSYS_PART_BLEND_FUNC_DEST", new ConstantSymbol("PSYS_PART_BLEND_FUNC_DEST", SymbolTable.INT, "25")},
			{"PSYS_PART_BF_ONE", new ConstantSymbol("PSYS_PART_BF_ONE", SymbolTable.INT, "0")},
			{"PSYS_PART_BF_ZERO", new ConstantSymbol("PSYS_PART_BF_ZERO", SymbolTable.INT, "1")},
			{"PSYS_PART_BF_DEST_COLOR", new ConstantSymbol("PSYS_PART_BF_DEST_COLOR", SymbolTable.INT, "2")},
			{"PSYS_PART_BF_SOURCE_COLOR", new ConstantSymbol("PSYS_PART_BF_SOURCE_COLOR", SymbolTable.INT, "3")},
			{"PSYS_PART_BF_ONE_MINUS_DEST_COLOR", new ConstantSymbol("PSYS_PART_BF_ONE_MINUS_DEST_COLOR", SymbolTable.INT, "4")},
			{"PSYS_PART_BF_ONE_MINUS_SOURCE_COLOR", new ConstantSymbol("PSYS_PART_BF_ONE_MINUS_SOURCE_COLOR", SymbolTable.INT, "5")},
			{"PSYS_PART_BF_SOURCE_ALPHA", new ConstantSymbol("PSYS_PART_BF_SOURCE_ALPHA", SymbolTable.INT, "7")},
			{"PSYS_PART_BF_ONE_MINUS_SOURCE_ALPHA", new ConstantSymbol("PSYS_PART_BF_ONE_MINUS_SOURCE_ALPHA", SymbolTable.INT, "9")},
			{"PSYS_SRC_MAX_AGE", new ConstantSymbol("PSYS_SRC_MAX_AGE", SymbolTable.INT, "19")},
            {"PSYS_PART_MAX_AGE", new ConstantSymbol("PSYS_PART_MAX_AGE", SymbolTable.INT, "7")},
			{"PSYS_SRC_BURST_RATE", new ConstantSymbol("PSYS_SRC_BURST_RATE", SymbolTable.INT, "13")},
			{"PSYS_SRC_BURST_PART_COUNT", new ConstantSymbol("PSYS_SRC_BURST_PART_COUNT", SymbolTable.INT, "15")},
            {"PSYS_SRC_ACCEL", new ConstantSymbol("PSYS_SRC_ACCEL", SymbolTable.INT, "8")},
			{"PSYS_SRC_OMEGA", new ConstantSymbol("PSYS_SRC_OMEGA", SymbolTable.INT, "21")},
            {"PSYS_SRC_BURST_SPEED_MIN", new ConstantSymbol("PSYS_SRC_BURST_SPEED_MIN", SymbolTable.INT, "17")},
            {"PSYS_SRC_BURST_SPEED_MAX", new ConstantSymbol("PSYS_SRC_BURST_SPEED_MAX", SymbolTable.INT, "18")},
            {"VEHICLE_TYPE_NONE", new ConstantSymbol("VEHICLE_TYPE_NONE", SymbolTable.INT, "0")},
            {"VEHICLE_TYPE_SLED", new ConstantSymbol("VEHICLE_TYPE_SLED", SymbolTable.INT, "1")},
            {"VEHICLE_TYPE_CAR", new ConstantSymbol("VEHICLE_TYPE_CAR", SymbolTable.INT, "2")},
            {"VEHICLE_TYPE_BOAT", new ConstantSymbol("VEHICLE_TYPE_BOAT", SymbolTable.INT, "3")},
            {"VEHICLE_TYPE_AIRPLANE", new ConstantSymbol("VEHICLE_TYPE_AIRPLANE", SymbolTable.INT, "4")},
            {"VEHICLE_TYPE_BALLOON", new ConstantSymbol("VEHICLE_TYPE_BALLOON", SymbolTable.INT, "5")},
            {"VEHICLE_TYPE_SAILBOAT", new ConstantSymbol("VEHICLE_TYPE_SAILBOAT", SymbolTable.INT, "10001")},
            {"VEHICLE_TYPE_MOTORCYCLE", new ConstantSymbol("VEHICLE_TYPE_MOTORCYCLE", SymbolTable.INT, "10002")},
            {"VEHICLE_LINEAR_FRICTION_TIMESCALE", new ConstantSymbol("VEHICLE_LINEAR_FRICTION_TIMESCALE", SymbolTable.INT, "16")},
            {"VEHICLE_ANGULAR_FRICTION_TIMESCALE", new ConstantSymbol("VEHICLE_ANGULAR_FRICTION_TIMESCALE", SymbolTable.INT, "17")},
            {"VEHICLE_LINEAR_MOTOR_DIRECTION", new ConstantSymbol("VEHICLE_LINEAR_MOTOR_DIRECTION", SymbolTable.INT, "18")},
            {"VEHICLE_LINEAR_MOTOR_OFFSET", new ConstantSymbol("VEHICLE_LINEAR_MOTOR_OFFSET", SymbolTable.INT, "20")},
            {"VEHICLE_ANGULAR_MOTOR_DIRECTION", new ConstantSymbol("VEHICLE_ANGULAR_MOTOR_DIRECTION", SymbolTable.INT, "19")},
            {"VEHICLE_HOVER_HEIGHT", new ConstantSymbol("VEHICLE_HOVER_HEIGHT", SymbolTable.INT, "24")},
            {"VEHICLE_HOVER_EFFICIENCY", new ConstantSymbol("VEHICLE_HOVER_EFFICIENCY", SymbolTable.INT, "25")},
            {"VEHICLE_HOVER_TIMESCALE", new ConstantSymbol("VEHICLE_HOVER_TIMESCALE", SymbolTable.INT, "26")},
            {"VEHICLE_BUOYANCY", new ConstantSymbol("VEHICLE_BUOYANCY", SymbolTable.INT, "27")},
            {"VEHICLE_LINEAR_DEFLECTION_EFFICIENCY", new ConstantSymbol("VEHICLE_LINEAR_DEFLECTION_EFFICIENCY", SymbolTable.INT, "28")},
            {"VEHICLE_LINEAR_DEFLECTION_TIMESCALE", new ConstantSymbol("VEHICLE_LINEAR_DEFLECTION_TIMESCALE", SymbolTable.INT, "29")},
            {"VEHICLE_LINEAR_MOTOR_TIMESCALE", new ConstantSymbol("VEHICLE_LINEAR_MOTOR_TIMESCALE", SymbolTable.INT, "30")},
            {"VEHICLE_LINEAR_MOTOR_DECAY_TIMESCALE", new ConstantSymbol("VEHICLE_LINEAR_MOTOR_DECAY_TIMESCALE", SymbolTable.INT, "31")},
            {"VEHICLE_ANGULAR_DEFLECTION_EFFICIENCY", new ConstantSymbol("VEHICLE_ANGULAR_DEFLECTION_EFFICIENCY", SymbolTable.INT, "32")},
            {"VEHICLE_ANGULAR_DEFLECTION_TIMESCALE", new ConstantSymbol("VEHICLE_ANGULAR_DEFLECTION_TIMESCALE", SymbolTable.INT, "33")},
            {"VEHICLE_ANGULAR_MOTOR_TIMESCALE", new ConstantSymbol("VEHICLE_ANGULAR_MOTOR_TIMESCALE", SymbolTable.INT, "34")},
            {"VEHICLE_ANGULAR_MOTOR_DECAY_TIMESCALE", new ConstantSymbol("VEHICLE_ANGULAR_MOTOR_DECAY_TIMESCALE", SymbolTable.INT, "35")},
            {"VEHICLE_VERTICAL_ATTRACTION_EFFICIENCY", new ConstantSymbol("VEHICLE_VERTICAL_ATTRACTION_EFFICIENCY", SymbolTable.INT, "36")},
            {"VEHICLE_VERTICAL_ATTRACTION_TIMESCALE", new ConstantSymbol("VEHICLE_VERTICAL_ATTRACTION_TIMESCALE", SymbolTable.INT, "37")},
            {"VEHICLE_BANKING_EFFICIENCY", new ConstantSymbol("VEHICLE_BANKING_EFFICIENCY", SymbolTable.INT, "38")},
            {"VEHICLE_BANKING_MIX", new ConstantSymbol("VEHICLE_BANKING_MIX", SymbolTable.INT, "39")},
            {"VEHICLE_BANKING_TIMESCALE", new ConstantSymbol("VEHICLE_BANKING_TIMESCALE", SymbolTable.INT, "40")},
            {"VEHICLE_MOUSELOOK_AZIMUTH", new ConstantSymbol("VEHICLE_MOUSELOOK_AZIMUTH", SymbolTable.INT, "11001")},
            {"VEHICLE_MOUSELOOK_ALTITUDE", new ConstantSymbol("VEHICLE_MOUSELOOK_ALTITUDE", SymbolTable.INT, "11002")},
            {"VEHICLE_BANKING_AZIMUTH", new ConstantSymbol("VEHICLE_BANKING_AZIMUTH", SymbolTable.INT, "11003")},
            {"VEHICLE_DISABLE_MOTORS_HEIGHT", new ConstantSymbol("VEHICLE_DISABLE_MOTORS_HEIGHT", SymbolTable.INT, "11004")},
            {"VEHICLE_DISABLE_MOTORS_DELAY", new ConstantSymbol("VEHICLE_DISABLE_MOTORS_DELAY", SymbolTable.INT, "11005")},
            {"VEHICLE_INVERTED_BANKING_MODIFIER", new ConstantSymbol("VEHICLE_INVERTED_BANKING_MODIFIER", SymbolTable.INT, "11006")},
            {"VEHICLE_REFERENCE_FRAME", new ConstantSymbol("VEHICLE_REFERENCE_FRAME", SymbolTable.INT, "44")},
            {"VEHICLE_LINEAR_WIND_EFFICIENCY", new ConstantSymbol("VEHICLE_LINEAR_WIND_EFFICIENCY", SymbolTable.INT, "12001")},
            {"VEHICLE_ANGULAR_WIND_EFFICIENCY", new ConstantSymbol("VEHICLE_ANGULAR_WIND_EFFICIENCY", SymbolTable.INT, "12002")},
            {"VEHICLE_FLAG_NO_DEFLECTION_UP", new ConstantSymbol("VEHICLE_FLAG_NO_DEFLECTION_UP", SymbolTable.INT, "1")},
            {"VEHICLE_FLAG_LIMIT_ROLL_ONLY", new ConstantSymbol("VEHICLE_FLAG_LIMIT_ROLL_ONLY", SymbolTable.INT, "2")},
            {"VEHICLE_FLAG_HOVER_WATER_ONLY", new ConstantSymbol("VEHICLE_FLAG_HOVER_WATER_ONLY", SymbolTable.INT, "4")},
            {"VEHICLE_FLAG_HOVER_TERRAIN_ONLY", new ConstantSymbol("VEHICLE_FLAG_HOVER_TERRAIN_ONLY", SymbolTable.INT, "8")},
            {"VEHICLE_FLAG_HOVER_GLOBAL_HEIGHT", new ConstantSymbol("VEHICLE_FLAG_HOVER_GLOBAL_HEIGHT", SymbolTable.INT, "16")},
            {"VEHICLE_FLAG_HOVER_UP_ONLY", new ConstantSymbol("VEHICLE_FLAG_HOVER_UP_ONLY", SymbolTable.INT, "32")},
            {"VEHICLE_FLAG_LIMIT_MOTOR_UP", new ConstantSymbol("VEHICLE_FLAG_LIMIT_MOTOR_UP", SymbolTable.INT, "64")},
            {"VEHICLE_FLAG_MOUSELOOK_STEER", new ConstantSymbol("VEHICLE_FLAG_MOUSELOOK_STEER", SymbolTable.INT, "128")},
            {"VEHICLE_FLAG_MOUSELOOK_BANK", new ConstantSymbol("VEHICLE_FLAG_MOUSELOOK_BANK", SymbolTable.INT, "256")},
            {"VEHICLE_FLAG_CAMERA_DECOUPLED", new ConstantSymbol("VEHICLE_FLAG_CAMERA_DECOUPLED", SymbolTable.INT, "512")},
            {"VEHICLE_FLAG_REACT_TO_CURRENTS", new ConstantSymbol("VEHICLE_FLAG_REACT_TO_CURRENTS", SymbolTable.INT, "65536")}, // 0x10000
            {"VEHICLE_FLAG_REACT_TO_WIND", new ConstantSymbol("VEHICLE_FLAG_REACT_TO_WIND", SymbolTable.INT, "131072")},        // 0x20000
            {"VEHICLE_FLAG_LIMIT_MOTOR_DOWN", new ConstantSymbol("VEHICLE_FLAG_LIMIT_MOTOR_DOWN", SymbolTable.INT, "262144")},  // 0x40000
            {"VEHICLE_FLAG_MOUSEPOINT_STEER", new ConstantSymbol("VEHICLE_FLAG_MOUSEPOINT_STEER", SymbolTable.INT, "1048576")}, // 0x100000
            {"VEHICLE_FLAG_MOUSEPOINT_BANK", new ConstantSymbol("VEHICLE_FLAG_MOUSEPOINT_BANK", SymbolTable.INT, "2097152")},   // 0x200000
            {"INVENTORY_ALL", new ConstantSymbol("INVENTORY_ALL", SymbolTable.INT, "-1")},
            {"INVENTORY_NONE", new ConstantSymbol("INVENTORY_NONE", SymbolTable.INT, "-1")},
            {"INVENTORY_TEXTURE", new ConstantSymbol("INVENTORY_TEXTURE", SymbolTable.INT, "0")},
            {"INVENTORY_SOUND", new ConstantSymbol("INVENTORY_SOUND", SymbolTable.INT, "1")},
            {"INVENTORY_LANDMARK", new ConstantSymbol("INVENTORY_LANDMARK", SymbolTable.INT, "3")},
            {"INVENTORY_CLOTHING", new ConstantSymbol("INVENTORY_CLOTHING", SymbolTable.INT, "5")},
            {"INVENTORY_OBJECT", new ConstantSymbol("INVENTORY_OBJECT", SymbolTable.INT, "6")},
            {"INVENTORY_NOTECARD", new ConstantSymbol("INVENTORY_NOTECARD", SymbolTable.INT, "7")},
            {"INVENTORY_SCRIPT", new ConstantSymbol("INVENTORY_SCRIPT", SymbolTable.INT, "10")},
            {"INVENTORY_BODYPART", new ConstantSymbol("INVENTORY_BODYPART", SymbolTable.INT, "13")},
            {"INVENTORY_ANIMATION", new ConstantSymbol("INVENTORY_ANIMATION", SymbolTable.INT, "20")},
            {"INVENTORY_GESTURE", new ConstantSymbol("INVENTORY_GESTURE", SymbolTable.INT, "21")},
            {"ATTACH_CHEST", new ConstantSymbol("ATTACH_CHEST", SymbolTable.INT, "1")},
            {"ATTACH_HEAD", new ConstantSymbol("ATTACH_HEAD", SymbolTable.INT, "2")},
            {"ATTACH_LSHOULDER", new ConstantSymbol("ATTACH_LSHOULDER", SymbolTable.INT, "3")},
            {"ATTACH_RSHOULDER", new ConstantSymbol("ATTACH_RSHOULDER", SymbolTable.INT, "4")},
            {"ATTACH_LHAND", new ConstantSymbol("ATTACH_LHAND", SymbolTable.INT, "5")},
            {"ATTACH_RHAND", new ConstantSymbol("ATTACH_RHAND", SymbolTable.INT, "6")},
            {"ATTACH_LFOOT", new ConstantSymbol("ATTACH_LFOOT", SymbolTable.INT, "7")},
            {"ATTACH_RFOOT", new ConstantSymbol("ATTACH_RFOOT", SymbolTable.INT, "8")},
            {"ATTACH_BACK", new ConstantSymbol("ATTACH_BACK", SymbolTable.INT, "9")},
            {"ATTACH_PELVIS", new ConstantSymbol("ATTACH_PELVIS", SymbolTable.INT, "10")},
            {"ATTACH_MOUTH", new ConstantSymbol("ATTACH_MOUTH", SymbolTable.INT, "11")},
            {"ATTACH_CHIN", new ConstantSymbol("ATTACH_CHIN", SymbolTable.INT, "12")},
            {"ATTACH_LEAR", new ConstantSymbol("ATTACH_LEAR", SymbolTable.INT, "13")},
            {"ATTACH_REAR", new ConstantSymbol("ATTACH_REAR", SymbolTable.INT, "14")},
            {"ATTACH_LEYE", new ConstantSymbol("ATTACH_LEYE", SymbolTable.INT, "15")},
            {"ATTACH_REYE", new ConstantSymbol("ATTACH_REYE", SymbolTable.INT, "16")},
            {"ATTACH_NOSE", new ConstantSymbol("ATTACH_NOSE", SymbolTable.INT, "17")},
            {"ATTACH_RUARM", new ConstantSymbol("ATTACH_RUARM", SymbolTable.INT, "18")},
            {"ATTACH_RLARM", new ConstantSymbol("ATTACH_RLARM", SymbolTable.INT, "19")},
            {"ATTACH_LUARM", new ConstantSymbol("ATTACH_LUARM", SymbolTable.INT, "20")},
            {"ATTACH_LLARM", new ConstantSymbol("ATTACH_LLARM", SymbolTable.INT, "21")},
            {"ATTACH_RHIP", new ConstantSymbol("ATTACH_RHIP", SymbolTable.INT, "22")},
            {"ATTACH_RULEG", new ConstantSymbol("ATTACH_RULEG", SymbolTable.INT, "23")},
            {"ATTACH_RLLEG", new ConstantSymbol("ATTACH_RLLEG", SymbolTable.INT, "24")},
            {"ATTACH_LHIP", new ConstantSymbol("ATTACH_LHIP", SymbolTable.INT, "25")},
            {"ATTACH_LULEG", new ConstantSymbol("ATTACH_LULEG", SymbolTable.INT, "26")},
            {"ATTACH_LLLEG", new ConstantSymbol("ATTACH_LLLEG", SymbolTable.INT, "27")},
            {"ATTACH_BELLY", new ConstantSymbol("ATTACH_BELLY", SymbolTable.INT, "28")},
            // RPEC and LPEC are reversed but rather than fix them, LL chose to leave them as is and add new ones.
            // So ATTACH_RPEC != ATTACH_RIGHT_PEC and ATTACH_LPEC != ATTACH_LEFT_PEC
            // See https://jira.secondlife.com/browse/SVC-580 for more.
            {"ATTACH_RPEC", new ConstantSymbol("ATTACH_RPEC", SymbolTable.INT, "29")},
            {"ATTACH_LEFT_PEC", new ConstantSymbol("ATTACH_LEFT_PEC", SymbolTable.INT, "29")},
            {"ATTACH_LPEC", new ConstantSymbol("ATTACH_LPEC", SymbolTable.INT, "30")},
            {"ATTACH_RIGHT_PEC", new ConstantSymbol("ATTACH_RIGHT_PEC", SymbolTable.INT, "30")},
            {"ATTACH_HUD_CENTER_2", new ConstantSymbol("ATTACH_HUD_CENTER_2", SymbolTable.INT, "31")},
            {"ATTACH_HUD_TOP_RIGHT", new ConstantSymbol("ATTACH_HUD_TOP_RIGHT", SymbolTable.INT, "32")},
            {"ATTACH_HUD_TOP_CENTER", new ConstantSymbol("ATTACH_HUD_TOP_CENTER", SymbolTable.INT, "33")},
            {"ATTACH_HUD_TOP_LEFT", new ConstantSymbol("ATTACH_HUD_TOP_LEFT", SymbolTable.INT, "34")},
            {"ATTACH_HUD_CENTER_1", new ConstantSymbol("ATTACH_HUD_CENTER_1", SymbolTable.INT, "35")},
            {"ATTACH_HUD_BOTTOM_LEFT", new ConstantSymbol("ATTACH_HUD_BOTTOM_LEFT", SymbolTable.INT, "36")},
            {"ATTACH_HUD_BOTTOM", new ConstantSymbol("ATTACH_HUD_BOTTOM", SymbolTable.INT, "37")},
            {"ATTACH_HUD_BOTTOM_RIGHT", new ConstantSymbol("ATTACH_HUD_BOTTOM_RIGHT", SymbolTable.INT, "38")},
            {"ATTACH_NECK", new ConstantSymbol("ATTACH_NECK", SymbolTable.INT, "39")},                      // identifier name not yet final https://jira.secondlife.com/browse/SCR-217
            {"ATTACH_AVATAR_CENTER", new ConstantSymbol("ATTACH_AVATAR_CENTER", SymbolTable.INT, "40")},    // identifier name not yet final https://jira.secondlife.com/browse/SCR-217
            {"LAND_LEVEL", new ConstantSymbol("LAND_LEVEL", SymbolTable.INT, "0")},
            {"LAND_RAISE", new ConstantSymbol("LAND_RAISE", SymbolTable.INT, "1")},
            {"LAND_LOWER", new ConstantSymbol("LAND_LOWER", SymbolTable.INT, "2")},
            {"LAND_SMOOTH", new ConstantSymbol("LAND_SMOOTH", SymbolTable.INT, "3")},
            {"LAND_NOISE", new ConstantSymbol("LAND_NOISE", SymbolTable.INT, "4")},
            {"LAND_REVERT", new ConstantSymbol("LAND_REVERT", SymbolTable.INT, "5")},
            {"LAND_SMALL_BRUSH", new ConstantSymbol("LAND_SMALL_BRUSH", SymbolTable.INT, "1")},
            {"LAND_MEDIUM_BRUSH", new ConstantSymbol("LAND_MEDIUM_BRUSH", SymbolTable.INT, "2")},
            {"LAND_LARGE_BRUSH", new ConstantSymbol("LAND_LARGE_BRUSH", SymbolTable.INT, "3")},
            {"DATA_ONLINE", new ConstantSymbol("DATA_ONLINE", SymbolTable.INT, "1")},
            {"DATA_NAME", new ConstantSymbol("DATA_NAME", SymbolTable.INT, "2")},
            {"DATA_BORN", new ConstantSymbol("DATA_BORN", SymbolTable.INT, "3")},
            {"DATA_RATING", new ConstantSymbol("DATA_RATING", SymbolTable.INT, "4")},
            {"DATA_SIM_POS", new ConstantSymbol("DATA_SIM_POS", SymbolTable.INT, "5")},
            {"DATA_SIM_STATUS", new ConstantSymbol("DATA_SIM_STATUS", SymbolTable.INT, "6")},
            {"DATA_SIM_RATING", new ConstantSymbol("DATA_SIM_RATING", SymbolTable.INT, "7")},
            {"DATA_PAYINFO", new ConstantSymbol("DATA_PAYINFO", SymbolTable.INT, "8")},
            {"DATA_SIM_RELEASE", new ConstantSymbol("DATA_SIM_RELEASE", SymbolTable.INT, "128")},
            {"DATA_ACCOUNT_TYPE", new ConstantSymbol("DATA_ACCOUNT_TYPE", SymbolTable.INT, "11001")},
            {"ANIM_ON", new ConstantSymbol("ANIM_ON", SymbolTable.INT, "1")},
            {"LOOP", new ConstantSymbol("LOOP", SymbolTable.INT, "2")},
            {"REVERSE", new ConstantSymbol("REVERSE", SymbolTable.INT, "4")},
            {"PING_PONG", new ConstantSymbol("PING_PONG", SymbolTable.INT, "8")},
            {"SMOOTH", new ConstantSymbol("SMOOTH", SymbolTable.INT, "16")},
            {"ROTATE", new ConstantSymbol("ROTATE", SymbolTable.INT, "32")},
            {"SCALE", new ConstantSymbol("SCALE", SymbolTable.INT, "64")},
            {"ALL_SIDES", new ConstantSymbol("ALL_SIDES", SymbolTable.INT, "-1")},
            {"LINK_SET", new ConstantSymbol("LINK_SET", SymbolTable.INT, "-1")},
            {"LINK_ROOT", new ConstantSymbol("LINK_ROOT", SymbolTable.INT, "1")},
            {"LINK_ALL_OTHERS", new ConstantSymbol("LINK_ALL_OTHERS", SymbolTable.INT, "-2")},
            {"LINK_ALL_CHILDREN", new ConstantSymbol("LINK_ALL_CHILDREN", SymbolTable.INT, "-3")},
            {"LINK_THIS", new ConstantSymbol("LINK_THIS", SymbolTable.INT, "-4")},
            {"CHANGED_INVENTORY", new ConstantSymbol("CHANGED_INVENTORY", SymbolTable.INT, "1")},
            {"CHANGED_COLOR", new ConstantSymbol("CHANGED_COLOR", SymbolTable.INT, "2")},
            {"CHANGED_SHAPE", new ConstantSymbol("CHANGED_SHAPE", SymbolTable.INT, "4")},
            {"CHANGED_SCALE", new ConstantSymbol("CHANGED_SCALE", SymbolTable.INT, "8")},
            {"CHANGED_TEXTURE", new ConstantSymbol("CHANGED_TEXTURE", SymbolTable.INT, "16")},
            {"CHANGED_LINK", new ConstantSymbol("CHANGED_LINK", SymbolTable.INT, "32")},
            {"CHANGED_ALLOWED_DROP", new ConstantSymbol("CHANGED_ALLOWED_DROP", SymbolTable.INT, "64")},
            {"CHANGED_OWNER", new ConstantSymbol("CHANGED_OWNER", SymbolTable.INT, "128")},
            {"CHANGED_REGION", new ConstantSymbol("CHANGED_REGION", SymbolTable.INT, "256")},
            {"CHANGED_TELEPORT", new ConstantSymbol("CHANGED_TELEPORT", SymbolTable.INT, "512")},
            {"CHANGED_REGION_START", new ConstantSymbol("CHANGED_REGION_START", SymbolTable.INT, "1024")},
            {"CHANGED_REGION_RESTART", new ConstantSymbol("CHANGED_REGION_RESTART", SymbolTable.INT, "1024")},
            {"CHANGED_MEDIA", new ConstantSymbol("CHANGED_MEDIA", SymbolTable.INT, "2048")},
            {"CHANGED_ANIMATION", new ConstantSymbol("CHANGED_ANIMATION", SymbolTable.INT, "16384")},   // see https://jira.secondlife.com/browse/SVC-408 and comments
            {"TYPE_INVALID", new ConstantSymbol("TYPE_INVALID", SymbolTable.INT, "0")},
            {"TYPE_INTEGER", new ConstantSymbol("TYPE_INTEGER", SymbolTable.INT, "1")},
            {"TYPE_FLOAT", new ConstantSymbol("TYPE_FLOAT", SymbolTable.INT, "2")},
            {"TYPE_STRING", new ConstantSymbol("TYPE_STRING", SymbolTable.INT, "3")},
            {"TYPE_KEY", new ConstantSymbol("TYPE_KEY", SymbolTable.INT, "4")},
            {"TYPE_VECTOR", new ConstantSymbol("TYPE_VECTOR", SymbolTable.INT, "5")},
            {"TYPE_ROTATION", new ConstantSymbol("TYPE_ROTATION", SymbolTable.INT, "6")},
            {"REMOTE_DATA_CHANNEL", new ConstantSymbol("REMOTE_DATA_CHANNEL", SymbolTable.INT, "1")},
            {"REMOTE_DATA_REQUEST", new ConstantSymbol("REMOTE_DATA_REQUEST", SymbolTable.INT, "2")},
            {"REMOTE_DATA_REPLY", new ConstantSymbol("REMOTE_DATA_REPLY", SymbolTable.INT, "3")},
            {"HTTP_METHOD", new ConstantSymbol("HTTP_METHOD", SymbolTable.INT, "0")},
            {"HTTP_MIMETYPE", new ConstantSymbol("HTTP_MIMETYPE", SymbolTable.INT, "1")},
            {"HTTP_BODY_MAXLENGTH", new ConstantSymbol("HTTP_BODY_MAXLENGTH", SymbolTable.INT, "2")},
            {"HTTP_VERIFY_CERT", new ConstantSymbol("HTTP_VERIFY_CERT", SymbolTable.INT, "3")},
            {"HTTP_VERBOSE_THROTTLE", new ConstantSymbol("HTTP_VERBOSE_THROTTLE", SymbolTable.INT, "4")},
            {"HTTP_CUSTOM_HEADER", new ConstantSymbol("HTTP_CUSTOM_HEADER", SymbolTable.INT, "5")},
            {"HTTP_PRAGMA_NO_CACHE", new ConstantSymbol("HTTP_PRAGMA_NO_CACHE", SymbolTable.INT, "6")},
            {"CONTENT_TYPE_TEXT", new ConstantSymbol("CONTENT_TYPE_TEXT", SymbolTable.INT, "0")},
            {"CONTENT_TYPE_HTML", new ConstantSymbol("CONTENT_TYPE_HTML", SymbolTable.INT, "1")},
            {"CONTENT_TYPE_XML", new ConstantSymbol("CONTENT_TYPE_XML", SymbolTable.INT, "2")},
            {"CONTENT_TYPE_XHTML", new ConstantSymbol("CONTENT_TYPE_XHTML", SymbolTable.INT, "3")},
            {"CONTENT_TYPE_ATOM", new ConstantSymbol("CONTENT_TYPE_ATOM", SymbolTable.INT, "4")},
            {"CONTENT_TYPE_JSON", new ConstantSymbol("CONTENT_TYPE_JSON", SymbolTable.INT, "5")},
            {"CONTENT_TYPE_LLSD", new ConstantSymbol("CONTENT_TYPE_LLSD", SymbolTable.INT, "6")},
            {"CONTENT_TYPE_FORM", new ConstantSymbol("CONTENT_TYPE_FORM", SymbolTable.INT, "7")},
            {"CONTENT_TYPE_RSS", new ConstantSymbol("CONTENT_TYPE_RSS", SymbolTable.INT, "8")},
            {"JSON_INVALID", new ConstantSymbol("JSON_INVALID", SymbolTable.STRING, "\uFDD0")},
            {"JSON_OBJECT", new ConstantSymbol("JSON_OBJECT", SymbolTable.STRING, "\uFDD1")},
            {"JSON_ARRAY", new ConstantSymbol("JSON_ARRAY", SymbolTable.STRING, "\uFDD2")},
            {"JSON_NUMBER", new ConstantSymbol("JSON_NUMBER", SymbolTable.STRING, "\uFDD3")},
            {"JSON_STRING", new ConstantSymbol("JSON_STRING", SymbolTable.STRING, "\uFDD4")},
            {"JSON_NULL", new ConstantSymbol("JSON_NULL", SymbolTable.STRING, "\uFDD5")},
            {"JSON_TRUE", new ConstantSymbol("JSON_TRUE", SymbolTable.STRING, "\uFDD6")},
            {"JSON_FALSE", new ConstantSymbol("JSON_FALSE", SymbolTable.STRING, "\uFDD7")},
            {"JSON_DELETE", new ConstantSymbol("JSON_DELETE", SymbolTable.STRING, "\uFDD8")},
            {"JSON_APPEND", new ConstantSymbol("JSON_APPEND", SymbolTable.INT, "-1")},
            {"PRIM_MATERIAL", new ConstantSymbol("PRIM_MATERIAL", SymbolTable.INT, "2")},
            {"PRIM_PHYSICS", new ConstantSymbol("PRIM_PHYSICS", SymbolTable.INT, "3")},
            {"PRIM_TEMP_ON_REZ", new ConstantSymbol("PRIM_TEMP_ON_REZ", SymbolTable.INT, "4")},
            {"PRIM_PHANTOM", new ConstantSymbol("PRIM_PHANTOM", SymbolTable.INT, "5")},
            {"PRIM_POSITION", new ConstantSymbol("PRIM_POSITION", SymbolTable.INT, "6")},
            {"PRIM_SIZE", new ConstantSymbol("PRIM_SIZE", SymbolTable.INT, "7")},
            {"PRIM_ROTATION", new ConstantSymbol("PRIM_ROTATION", SymbolTable.INT, "8")},
            {"PRIM_TYPE", new ConstantSymbol("PRIM_TYPE", SymbolTable.INT, "9")},
            {"PRIM_TEXTURE", new ConstantSymbol("PRIM_TEXTURE", SymbolTable.INT, "17")},
            {"PRIM_COLOR", new ConstantSymbol("PRIM_COLOR", SymbolTable.INT, "18")},
            {"PRIM_BUMP_SHINY", new ConstantSymbol("PRIM_BUMP_SHINY", SymbolTable.INT, "19")},
            {"PRIM_FULLBRIGHT", new ConstantSymbol("PRIM_FULLBRIGHT", SymbolTable.INT, "20")},
            {"PRIM_FLEXIBLE", new ConstantSymbol("PRIM_FLEXIBLE", SymbolTable.INT, "21")},
            {"PRIM_TEXGEN", new ConstantSymbol("PRIM_TEXGEN", SymbolTable.INT, "22")},
            {"PRIM_POINT_LIGHT", new ConstantSymbol("PRIM_POINT_LIGHT", SymbolTable.INT, "23")},
            {"PRIM_CAST_SHADOWS", new ConstantSymbol("PRIM_CAST_SHADOWS", SymbolTable.INT, "24")},
            {"PRIM_GLOW", new ConstantSymbol("PRIM_GLOW", SymbolTable.INT, "25")},
            {"PRIM_TEXT", new ConstantSymbol("PRIM_TEXT", SymbolTable.INT, "26")},
            {"PRIM_NAME", new ConstantSymbol("PRIM_NAME", SymbolTable.INT, "27")},
            {"PRIM_DESC", new ConstantSymbol("PRIM_DESC", SymbolTable.INT, "28")},
            {"PRIM_ROT_LOCAL", new ConstantSymbol("PRIM_ROT_LOCAL", SymbolTable.INT, "29")},
            
            {"PRIM_PHYSICS_SHAPE_TYPE", new ConstantSymbol("PRIM_PHYSICS_SHAPE_TYPE", SymbolTable.INT, "30")},
            {"PRIM_PHYSICS_SHAPE_PRIM", new ConstantSymbol("PRIM_PHYSICS_SHAPE_PRIM", SymbolTable.INT, "0")},
            {"PRIM_PHYSICS_SHAPE_CONVEX", new ConstantSymbol("PRIM_PHYSICS_SHAPE_CONVEX", SymbolTable.INT, "2")},
            {"PRIM_PHYSICS_SHAPE_NONE", new ConstantSymbol("PRIM_PHYSICS_SHAPE_NONE", SymbolTable.INT, "1")},

            {"PRIM_OMEGA", new ConstantSymbol("PRIM_OMEGA", SymbolTable.INT, "32")},
            {"PRIM_POS_LOCAL", new ConstantSymbol("PRIM_POS_LOCAL", SymbolTable.INT, "33")},
            {"PRIM_LINK_TARGET", new ConstantSymbol("PRIM_LINK_TARGET", SymbolTable.INT, "34")},
            {"PRIM_SLICE", new ConstantSymbol("PRIM_SLICE", SymbolTable.INT, "35")},

            {"PRIM_SPECULAR", new ConstantSymbol("PRIM_SPECULAR", SymbolTable.INT, "36")},
            {"PRIM_NORMAL", new ConstantSymbol("PRIM_NORMAL", SymbolTable.INT, "37")},
            {"PRIM_ALPHA_MODE", new ConstantSymbol("PRIM_ALPHA_MODE", SymbolTable.INT, "38")},

            {"IW_PRIM_ALPHA", new ConstantSymbol("IW_PRIM_ALPHA", SymbolTable.INT, "11001")},   // IW extensions to PRIM_* constants
            {"IW_PRIM_PROJECTOR",          new ConstantSymbol("IW_PRIM_PROJECTOR",          SymbolTable.INT, "11100")},
            {"IW_PRIM_PROJECTOR_ENABLED",  new ConstantSymbol("IW_PRIM_PROJECTOR_ENABLED",  SymbolTable.INT, "11101")},
            {"IW_PRIM_PROJECTOR_TEXTURE",  new ConstantSymbol("IW_PRIM_PROJECTOR_TEXTURE",  SymbolTable.INT, "11102")},
            {"IW_PRIM_PROJECTOR_FOV",      new ConstantSymbol("IW_PRIM_PROJECTOR_FOV",      SymbolTable.INT, "11103")},
            {"IW_PRIM_PROJECTOR_FOCUS",    new ConstantSymbol("IW_PRIM_PROJECTOR_FOCUS",    SymbolTable.INT, "11104")},
            {"IW_PRIM_PROJECTOR_AMBIENCE", new ConstantSymbol("IW_PRIM_PROJECTOR_AMBIENCE", SymbolTable.INT, "11105")},

            {"PRIM_TEXGEN_DEFAULT", new ConstantSymbol("PRIM_TEXGEN_DEFAULT", SymbolTable.INT, "0")},
            {"PRIM_TEXGEN_PLANAR", new ConstantSymbol("PRIM_TEXGEN_PLANAR", SymbolTable.INT, "1")},
            {"PRIM_TYPE_BOX", new ConstantSymbol("PRIM_TYPE_BOX", SymbolTable.INT, "0")},
            {"PRIM_TYPE_CYLINDER", new ConstantSymbol("PRIM_TYPE_CYLINDER", SymbolTable.INT, "1")},
            {"PRIM_TYPE_PRISM", new ConstantSymbol("PRIM_TYPE_PRISM", SymbolTable.INT, "2")},
            {"PRIM_TYPE_SPHERE", new ConstantSymbol("PRIM_TYPE_SPHERE", SymbolTable.INT, "3")},
            {"PRIM_TYPE_TORUS", new ConstantSymbol("PRIM_TYPE_TORUS", SymbolTable.INT, "4")},
            {"PRIM_TYPE_TUBE", new ConstantSymbol("PRIM_TYPE_TUBE", SymbolTable.INT, "5")},
            {"PRIM_TYPE_RING", new ConstantSymbol("PRIM_TYPE_RING", SymbolTable.INT, "6")},
            {"PRIM_TYPE_SCULPT", new ConstantSymbol("PRIM_TYPE_SCULPT", SymbolTable.INT, "7")},
            {"PRIM_HOLE_DEFAULT", new ConstantSymbol("PRIM_HOLE_DEFAULT", SymbolTable.INT, "0")},
            {"PRIM_HOLE_CIRCLE", new ConstantSymbol("PRIM_HOLE_CIRCLE", SymbolTable.INT, "16")},
            {"PRIM_HOLE_SQUARE", new ConstantSymbol("PRIM_HOLE_SQUARE", SymbolTable.INT, "32")},
            {"PRIM_HOLE_TRIANGLE", new ConstantSymbol("PRIM_HOLE_TRIANGLE", SymbolTable.INT, "48")},
            {"PRIM_MATERIAL_STONE", new ConstantSymbol("PRIM_MATERIAL_STONE", SymbolTable.INT, "0")},
            {"PRIM_MATERIAL_METAL", new ConstantSymbol("PRIM_MATERIAL_METAL", SymbolTable.INT, "1")},
            {"PRIM_MATERIAL_GLASS", new ConstantSymbol("PRIM_MATERIAL_GLASS", SymbolTable.INT, "2")},
            {"PRIM_MATERIAL_WOOD", new ConstantSymbol("PRIM_MATERIAL_WOOD", SymbolTable.INT, "3")},
            {"PRIM_MATERIAL_FLESH", new ConstantSymbol("PRIM_MATERIAL_FLESH", SymbolTable.INT, "4")},
            {"PRIM_MATERIAL_PLASTIC", new ConstantSymbol("PRIM_MATERIAL_PLASTIC", SymbolTable.INT, "5")},
            {"PRIM_MATERIAL_RUBBER", new ConstantSymbol("PRIM_MATERIAL_RUBBER", SymbolTable.INT, "6")},
            {"PRIM_MATERIAL_LIGHT", new ConstantSymbol("PRIM_MATERIAL_LIGHT", SymbolTable.INT, "7")},
            {"PRIM_SHINY_NONE", new ConstantSymbol("PRIM_SHINY_NONE", SymbolTable.INT, "0")},
            {"PRIM_SHINY_LOW", new ConstantSymbol("PRIM_SHINY_LOW", SymbolTable.INT, "1")},
            {"PRIM_SHINY_MEDIUM", new ConstantSymbol("PRIM_SHINY_MEDIUM", SymbolTable.INT, "2")},
            {"PRIM_SHINY_HIGH", new ConstantSymbol("PRIM_SHINY_HIGH", SymbolTable.INT, "3")},
            {"PRIM_BUMP_NONE", new ConstantSymbol("PRIM_BUMP_NONE", SymbolTable.INT, "0")},
            {"PRIM_BUMP_BRIGHT", new ConstantSymbol("PRIM_BUMP_BRIGHT", SymbolTable.INT, "1")},
            {"PRIM_BUMP_DARK", new ConstantSymbol("PRIM_BUMP_DARK", SymbolTable.INT, "2")},
            {"PRIM_BUMP_WOOD", new ConstantSymbol("PRIM_BUMP_WOOD", SymbolTable.INT, "3")},
            {"PRIM_BUMP_BARK", new ConstantSymbol("PRIM_BUMP_BARK", SymbolTable.INT, "4")},
            {"PRIM_BUMP_BRICKS", new ConstantSymbol("PRIM_BUMP_BRICKS", SymbolTable.INT, "5")},
            {"PRIM_BUMP_CHECKER", new ConstantSymbol("PRIM_BUMP_CHECKER", SymbolTable.INT, "6")},
            {"PRIM_BUMP_CONCRETE", new ConstantSymbol("PRIM_BUMP_CONCRETE", SymbolTable.INT, "7")},
            {"PRIM_BUMP_TILE", new ConstantSymbol("PRIM_BUMP_TILE", SymbolTable.INT, "8")},
            {"PRIM_BUMP_STONE", new ConstantSymbol("PRIM_BUMP_STONE", SymbolTable.INT, "9")},
            {"PRIM_BUMP_DISKS", new ConstantSymbol("PRIM_BUMP_DISKS", SymbolTable.INT, "10")},
            {"PRIM_BUMP_GRAVEL", new ConstantSymbol("PRIM_BUMP_GRAVEL", SymbolTable.INT, "11")},
            {"PRIM_BUMP_BLOBS", new ConstantSymbol("PRIM_BUMP_BLOBS", SymbolTable.INT, "12")},
            {"PRIM_BUMP_SIDING", new ConstantSymbol("PRIM_BUMP_SIDING", SymbolTable.INT, "13")},
            {"PRIM_BUMP_LARGETILE", new ConstantSymbol("PRIM_BUMP_LARGETILE", SymbolTable.INT, "14")},
            {"PRIM_BUMP_STUCCO", new ConstantSymbol("PRIM_BUMP_STUCCO", SymbolTable.INT, "15")},
            {"PRIM_BUMP_SUCTION", new ConstantSymbol("PRIM_BUMP_SUCTION", SymbolTable.INT, "16")},
            {"PRIM_BUMP_WEAVE", new ConstantSymbol("PRIM_BUMP_WEAVE", SymbolTable.INT, "17")},
            {"PRIM_SCULPT_TYPE_SPHERE", new ConstantSymbol("PRIM_SCULPT_TYPE_SPHERE", SymbolTable.INT, "1")},
            {"PRIM_SCULPT_TYPE_TORUS", new ConstantSymbol("PRIM_SCULPT_TYPE_TORUS", SymbolTable.INT, "2")},
            {"PRIM_SCULPT_TYPE_PLANE", new ConstantSymbol("PRIM_SCULPT_TYPE_PLANE", SymbolTable.INT, "3")},
            {"PRIM_SCULPT_TYPE_CYLINDER", new ConstantSymbol("PRIM_SCULPT_TYPE_CYLINDER", SymbolTable.INT, "4")},
            {"PRIM_SCULPT_FLAG_INVERT", new ConstantSymbol("PRIM_SCULPT_FLAG_INVERT", SymbolTable.INT, "64")},
            {"PRIM_SCULPT_FLAG_MIRROR", new ConstantSymbol("PRIM_SCULPT_FLAG_MIRROR", SymbolTable.INT, "128")},

            {"PRIM_ALPHA_MODE_NONE", new ConstantSymbol("PRIM_ALPHA_MODE_NONE", SymbolTable.INT, "0")},
            {"PRIM_ALPHA_MODE_BLEND", new ConstantSymbol("PRIM_ALPHA_MODE_BLEND", SymbolTable.INT, "1")},
            {"PRIM_ALPHA_MODE_MASK", new ConstantSymbol("PRIM_ALPHA_MODE_MASK", SymbolTable.INT, "2")},
            {"PRIM_ALPHA_MODE_EMISSIVE", new ConstantSymbol("PRIM_ALPHA_MODE_EMISSIVE", SymbolTable.INT, "3")},

            {"MASK_BASE", new ConstantSymbol("MASK_BASE", SymbolTable.INT, "0")},
            {"MASK_OWNER", new ConstantSymbol("MASK_OWNER", SymbolTable.INT, "1")},
            {"MASK_GROUP", new ConstantSymbol("MASK_GROUP", SymbolTable.INT, "2")},
            {"MASK_EVERYONE", new ConstantSymbol("MASK_EVERYONE", SymbolTable.INT, "3")},
            {"MASK_NEXT", new ConstantSymbol("MASK_NEXT", SymbolTable.INT, "4")},
            {"PERM_TRANSFER", new ConstantSymbol("PERM_TRANSFER", SymbolTable.INT, "8192")},
            {"PERM_MODIFY", new ConstantSymbol("PERM_MODIFY", SymbolTable.INT, "16384")},
            {"PERM_COPY", new ConstantSymbol("PERM_COPY", SymbolTable.INT, "32768")},
            {"PERM_MOVE", new ConstantSymbol("PERM_MOVE", SymbolTable.INT, "524288")},
            {"PERM_ALL", new ConstantSymbol("PERM_ALL", SymbolTable.INT, "2147483647")},
            {"PARCEL_MEDIA_COMMAND_STOP", new ConstantSymbol("PARCEL_MEDIA_COMMAND_STOP", SymbolTable.INT, "0")},
            {"PARCEL_MEDIA_COMMAND_PAUSE", new ConstantSymbol("PARCEL_MEDIA_COMMAND_PAUSE", SymbolTable.INT, "1")},
            {"PARCEL_MEDIA_COMMAND_PLAY", new ConstantSymbol("PARCEL_MEDIA_COMMAND_PLAY", SymbolTable.INT, "2")},
            {"PARCEL_MEDIA_COMMAND_LOOP", new ConstantSymbol("PARCEL_MEDIA_COMMAND_LOOP", SymbolTable.INT, "3")},
            {"PARCEL_MEDIA_COMMAND_TEXTURE", new ConstantSymbol("PARCEL_MEDIA_COMMAND_TEXTURE", SymbolTable.INT, "4")},
            {"PARCEL_MEDIA_COMMAND_URL", new ConstantSymbol("PARCEL_MEDIA_COMMAND_URL", SymbolTable.INT, "5")},
            {"PARCEL_MEDIA_COMMAND_TIME", new ConstantSymbol("PARCEL_MEDIA_COMMAND_TIME", SymbolTable.INT, "6")},
            {"PARCEL_MEDIA_COMMAND_AGENT", new ConstantSymbol("PARCEL_MEDIA_COMMAND_AGENT", SymbolTable.INT, "7")},
            {"PARCEL_MEDIA_COMMAND_UNLOAD", new ConstantSymbol("PARCEL_MEDIA_COMMAND_UNLOAD", SymbolTable.INT, "8")},
            {"PARCEL_MEDIA_COMMAND_AUTO_ALIGN", new ConstantSymbol("PARCEL_MEDIA_COMMAND_AUTO_ALIGN", SymbolTable.INT, "9")},
            {"PARCEL_MEDIA_COMMAND_TYPE", new ConstantSymbol("PARCEL_MEDIA_COMMAND_TYPE", SymbolTable.INT, "10")},
            {"PARCEL_MEDIA_COMMAND_SIZE", new ConstantSymbol("PARCEL_MEDIA_COMMAND_SIZE", SymbolTable.INT, "11")},
            {"PARCEL_MEDIA_COMMAND_DESC", new ConstantSymbol("PARCEL_MEDIA_COMMAND_DESC", SymbolTable.INT, "12")},
            {"PARCEL_FLAG_ALLOW_FLY", new ConstantSymbol("PARCEL_FLAG_ALLOW_FLY", SymbolTable.INT, "0x1")},
            {"PARCEL_FLAG_ALLOW_SCRIPTS", new ConstantSymbol("PARCEL_FLAG_ALLOW_SCRIPTS", SymbolTable.INT, "0x2")},
            {"PARCEL_FLAG_ALLOW_LANDMARK", new ConstantSymbol("PARCEL_FLAG_ALLOW_LANDMARK", SymbolTable.INT, "0x8")},
            {"PARCEL_FLAG_ALLOW_TERRAFORM", new ConstantSymbol("PARCEL_FLAG_ALLOW_TERRAFORM", SymbolTable.INT, "0x10")},
            {"PARCEL_FLAG_ALLOW_DAMAGE", new ConstantSymbol("PARCEL_FLAG_ALLOW_DAMAGE", SymbolTable.INT, "0x20")},
            {"PARCEL_FLAG_ALLOW_CREATE_OBJECTS", new ConstantSymbol("PARCEL_FLAG_ALLOW_CREATE_OBJECTS", SymbolTable.INT, "0x40")},
            {"PARCEL_FLAG_USE_ACCESS_GROUP", new ConstantSymbol("PARCEL_FLAG_USE_ACCESS_GROUP", SymbolTable.INT, "0x100")},
            {"PARCEL_FLAG_USE_ACCESS_LIST", new ConstantSymbol("PARCEL_FLAG_USE_ACCESS_LIST", SymbolTable.INT, "0x200")},
            {"PARCEL_FLAG_USE_BAN_LIST", new ConstantSymbol("PARCEL_FLAG_USE_BAN_LIST", SymbolTable.INT, "0x400")},
            {"PARCEL_FLAG_USE_LAND_PASS_LIST", new ConstantSymbol("PARCEL_FLAG_USE_LAND_PASS_LIST", SymbolTable.INT, "0x800")},
            {"PARCEL_FLAG_LOCAL_SOUND_ONLY", new ConstantSymbol("PARCEL_FLAG_LOCAL_SOUND_ONLY", SymbolTable.INT, "0x8000")},
            {"PARCEL_FLAG_RESTRICT_PUSHOBJECT", new ConstantSymbol("PARCEL_FLAG_RESTRICT_PUSHOBJECT", SymbolTable.INT, "0x200000")},
            {"PARCEL_FLAG_ALLOW_GROUP_SCRIPTS", new ConstantSymbol("PARCEL_FLAG_ALLOW_GROUP_SCRIPTS", SymbolTable.INT, "0x2000000")},
            {"PARCEL_FLAG_ALLOW_CREATE_GROUP_OBJECTS", new ConstantSymbol("PARCEL_FLAG_ALLOW_CREATE_GROUP_OBJECTS", SymbolTable.INT, "0x4000000")},
            {"PARCEL_FLAG_ALLOW_ALL_OBJECT_ENTRY", new ConstantSymbol("PARCEL_FLAG_ALLOW_ALL_OBJECT_ENTRY", SymbolTable.INT, "0x8000000")},
            {"PARCEL_FLAG_ALLOW_GROUP_OBJECT_ENTRY", new ConstantSymbol("PARCEL_FLAG_ALLOW_GROUP_OBJECT_ENTRY", SymbolTable.INT, "0x10000000")},
            {"REGION_FLAG_ALLOW_DAMAGE", new ConstantSymbol("REGION_FLAG_ALLOW_DAMAGE", SymbolTable.INT, "0x1")},
            {"REGION_FLAG_FIXED_SUN", new ConstantSymbol("REGION_FLAG_FIXED_SUN", SymbolTable.INT, "0x10")},
            {"REGION_FLAG_BLOCK_TERRAFORM", new ConstantSymbol("REGION_FLAG_BLOCK_TERRAFORM", SymbolTable.INT, "0x40")},
            {"REGION_FLAG_SANDBOX", new ConstantSymbol("REGION_FLAG_SANDBOX", SymbolTable.INT, "0x100")},
            {"REGION_FLAG_DISABLE_COLLISIONS", new ConstantSymbol("REGION_FLAG_DISABLE_COLLISIONS", SymbolTable.INT, "0x1000")},
            {"REGION_FLAG_DISABLE_PHYSICS", new ConstantSymbol("REGION_FLAG_DISABLE_PHYSICS", SymbolTable.INT, "0x4000")},
            {"REGION_FLAG_BLOCK_FLY", new ConstantSymbol("REGION_FLAG_BLOCK_FLY", SymbolTable.INT, "0x80000")},
            {"REGION_FLAG_ALLOW_DIRECT_TELEPORT", new ConstantSymbol("REGION_FLAG_ALLOW_DIRECT_TELEPORT", SymbolTable.INT, "0x100000")},
            {"REGION_FLAG_RESTRICT_PUSHOBJECT", new ConstantSymbol("REGION_FLAG_RESTRICT_PUSHOBJECT", SymbolTable.INT, "0x400000")},
            {"EOF", new ConstantSymbol("EOF", SymbolTable.STRING, "\\n\\n\\n")},
            {"PI", new ConstantSymbol("PI", SymbolTable.FLOAT, "3.14159274")},
            {"TWO_PI", new ConstantSymbol("TWO_PI", SymbolTable.FLOAT, "6.28318548")},
            {"PI_BY_TWO", new ConstantSymbol("PI_BY_TWO", SymbolTable.FLOAT, "1.57079637")},
            {"DEG_TO_RAD", new ConstantSymbol("DEG_TO_RAD", SymbolTable.FLOAT, "0.01745329238")},
            {"RAD_TO_DEG", new ConstantSymbol("RAD_TO_DEG", SymbolTable.FLOAT, "57.29578")},
            {"SQRT2", new ConstantSymbol("SQRT2", SymbolTable.FLOAT, "1.414213538")},
            {"STRING_TRIM_HEAD", new ConstantSymbol("STRING_TRIM_HEAD", SymbolTable.INT, "1")},
            {"STRING_TRIM_TAIL", new ConstantSymbol("STRING_TRIM_TAIL", SymbolTable.INT, "2")},
            {"STRING_TRIM", new ConstantSymbol("STRING_TRIM", SymbolTable.INT, "3")},
            {"LIST_STAT_RANGE", new ConstantSymbol("LIST_STAT_RANGE", SymbolTable.INT, "0")},
            {"LIST_STAT_MIN", new ConstantSymbol("LIST_STAT_MIN", SymbolTable.INT, "1")},
            {"LIST_STAT_MAX", new ConstantSymbol("LIST_STAT_MAX", SymbolTable.INT, "2")},
            {"LIST_STAT_MEAN", new ConstantSymbol("LIST_STAT_MEAN", SymbolTable.INT, "3")},
            {"LIST_STAT_MEDIAN", new ConstantSymbol("LIST_STAT_MEDIAN", SymbolTable.INT, "4")},
            {"LIST_STAT_STD_DEV", new ConstantSymbol("LIST_STAT_STD_DEV", SymbolTable.INT, "5")},
            {"LIST_STAT_SUM", new ConstantSymbol("LIST_STAT_SUM", SymbolTable.INT, "6")},
            {"LIST_STAT_SUM_SQUARES", new ConstantSymbol("LIST_STAT_SUM_SQUARES", SymbolTable.INT, "7")},
            {"LIST_STAT_NUM_COUNT", new ConstantSymbol("LIST_STAT_NUM_COUNT", SymbolTable.INT, "8")},
            {"LIST_STAT_GEOMETRIC_MEAN", new ConstantSymbol("LIST_STAT_GEOMETRIC_MEAN", SymbolTable.INT, "9")},
            {"LIST_STAT_HARMONIC_MEAN", new ConstantSymbol("LIST_STAT_HARMONIC_MEAN", SymbolTable.INT, "100")},
            {"PARCEL_COUNT_TOTAL", new ConstantSymbol("PARCEL_COUNT_TOTAL", SymbolTable.INT, "0")},
            {"PARCEL_COUNT_OWNER", new ConstantSymbol("PARCEL_COUNT_OWNER", SymbolTable.INT, "1")},
            {"PARCEL_COUNT_GROUP", new ConstantSymbol("PARCEL_COUNT_GROUP", SymbolTable.INT, "2")},
            {"PARCEL_COUNT_OTHER", new ConstantSymbol("PARCEL_COUNT_OTHER", SymbolTable.INT, "3")},
            {"PARCEL_COUNT_SELECTED", new ConstantSymbol("PARCEL_COUNT_SELECTED", SymbolTable.INT, "4")},
            {"PARCEL_COUNT_TEMP", new ConstantSymbol("PARCEL_COUNT_TEMP", SymbolTable.INT, "5")},
            {"DEBUG_CHANNEL", new ConstantSymbol("DEBUG_CHANNEL", SymbolTable.INT, "0x7FFFFFFF")},
            {"PUBLIC_CHANNEL", new ConstantSymbol("PUBLIC_CHANNEL", SymbolTable.INT, "0x00000000")},

            {"OBJECT_NAME", new ConstantSymbol("OBJECT_NAME", SymbolTable.INT, "1")},
            {"OBJECT_DESC", new ConstantSymbol("OBJECT_DESC", SymbolTable.INT, "2")},
            {"OBJECT_POS", new ConstantSymbol("OBJECT_POS", SymbolTable.INT, "3")},
            {"OBJECT_ROT", new ConstantSymbol("OBJECT_ROT", SymbolTable.INT, "4")},
            {"OBJECT_VELOCITY", new ConstantSymbol("OBJECT_VELOCITY", SymbolTable.INT, "5")},
            {"OBJECT_OWNER", new ConstantSymbol("OBJECT_OWNER", SymbolTable.INT, "6")},
            {"OBJECT_GROUP", new ConstantSymbol("OBJECT_GROUP", SymbolTable.INT, "7")},
            {"OBJECT_CREATOR", new ConstantSymbol("OBJECT_CREATOR", SymbolTable.INT, "8")},
            {"OBJECT_RUNNING_SCRIPT_COUNT", new ConstantSymbol("OBJECT_RUNNING_SCRIPT_COUNT", SymbolTable.INT, "9")},
            {"OBJECT_TOTAL_SCRIPT_COUNT", new ConstantSymbol("OBJECT_TOTAL_SCRIPT_COUNT", SymbolTable.INT, "10")},
            {"OBJECT_SCRIPT_MEMORY", new ConstantSymbol("OBJECT_SCRIPT_MEMORY", SymbolTable.INT, "11")},
            {"OBJECT_SCRIPT_TIME", new ConstantSymbol("OBJECT_SCRIPT_TIME", SymbolTable.INT, "12")},
            {"OBJECT_PRIM_EQUIVALENCE", new ConstantSymbol("OBJECT_PRIM_EQUIVALENCE", SymbolTable.INT, "13")},
            {"OBJECT_SERVER_COST", new ConstantSymbol("OBJECT_SERVER_COST", SymbolTable.INT, "14")},
            {"OBJECT_STREAMING_COST", new ConstantSymbol("OBJECT_STREAMING_COST", SymbolTable.INT, "15")},
            {"OBJECT_PHYSICS_COST", new ConstantSymbol("OBJECT_PHYSICS_COST", SymbolTable.INT, "16")},
            {"OBJECT_CHARACTER_TIME", new ConstantSymbol("OBJECT_CHARACTER_TIME", SymbolTable.INT, "17")},
            {"OBJECT_ROOT", new ConstantSymbol("OBJECT_ROOT", SymbolTable.INT, "18")},
            {"OBJECT_ATTACHED_POINT", new ConstantSymbol("OBJECT_ATTACHED_POINT", SymbolTable.INT, "19")},
            {"OBJECT_PATHFINDING_TYPE", new ConstantSymbol("OBJECT_PATHFINDING_TYPE", SymbolTable.INT, "20")},
            {"OBJECT_PHYSICS", new ConstantSymbol("OBJECT_PHYSICS", SymbolTable.INT, "21")},
            {"OBJECT_PHANTOM", new ConstantSymbol("OBJECT_PHANTOM", SymbolTable.INT, "22")},
            {"OBJECT_TEMP_ON_REZ", new ConstantSymbol("OBJECT_TEMP_ON_REZ", SymbolTable.INT, "23")},
            {"OBJECT_RENDER_WEIGHT", new ConstantSymbol("OBJECT_RENDER_WEIGHT", SymbolTable.INT, "24")},
            {"OBJECT_HOVER_HEIGHT", new ConstantSymbol("OBJECT_HOVER_HEIGHT", SymbolTable.INT, "25")},
            {"OBJECT_BODY_SHAPE_TYPE", new ConstantSymbol("OBJECT_BODY_SHAPE_TYPE", SymbolTable.INT, "26")},
            {"OBJECT_LAST_OWNER_ID", new ConstantSymbol("OBJECT_LAST_OWNER_ID", SymbolTable.INT, "27")},
            {"OBJECT_CLICK_ACTION", new ConstantSymbol("OBJECT_CLICK_ACTION", SymbolTable.INT, "28")},

            // IW extensions to the OBJECT_CONSTANTS at out-of-range unexpected values
            {"OBJECT_TOTAL_UPDATES", new ConstantSymbol("OBJECT_TOTAL_UPDATES", SymbolTable.INT, "11001")},

            {"OPT_OTHER", new ConstantSymbol("OPT_OTHER", SymbolTable.INT, "-1")},
            {"OPT_LEGACY_LINKSET", new ConstantSymbol("OPT_LEGACY_LINKSET", SymbolTable.INT, "0")},
            {"OPT_AVATAR", new ConstantSymbol("OPT_AVATAR", SymbolTable.INT, "1")},
            {"OPT_CHARACTER", new ConstantSymbol("OPT_CHARACTER", SymbolTable.INT, "2")},
            {"OPT_WALKABLE", new ConstantSymbol("OPT_WALKABLE", SymbolTable.INT, "3")},
            {"OPT_STATIC_OBSTACLE", new ConstantSymbol("OPT_STATIC_OBSTACLE", SymbolTable.INT, "4")},
            {"OPT_MATERIAL_VOLUME", new ConstantSymbol("OPT_MATERIAL_VOLUME", SymbolTable.INT, "5")},
            {"OPT_EXCLUSION_VOLUME", new ConstantSymbol("OPT_EXCLUSION_VOLUME", SymbolTable.INT, "6")},

            {"CAMERA_PITCH", new ConstantSymbol("CAMERA_PITCH", SymbolTable.INT, "0")},
            {"CAMERA_FOCUS_OFFSET", new ConstantSymbol("CAMERA_FOCUS_OFFSET", SymbolTable.INT, "1")},
            {"CAMERA_FOCUS_OFFSET_X", new ConstantSymbol("CAMERA_FOCUS_OFFSET_X", SymbolTable.INT, "2")},
            {"CAMERA_FOCUS_OFFSET_Y", new ConstantSymbol("CAMERA_FOCUS_OFFSET_Y", SymbolTable.INT, "3")},
            {"CAMERA_FOCUS_OFFSET_Z", new ConstantSymbol("CAMERA_FOCUS_OFFSET_Z", SymbolTable.INT, "4")},
            {"CAMERA_POSITION_LAG", new ConstantSymbol("CAMERA_POSITION_LAG", SymbolTable.INT, "5")},
            {"CAMERA_FOCUS_LAG", new ConstantSymbol("CAMERA_FOCUS_LAG", SymbolTable.INT, "6")},
            {"CAMERA_DISTANCE", new ConstantSymbol("CAMERA_DISTANCE", SymbolTable.INT, "7")},
            {"CAMERA_BEHINDNESS_ANGLE", new ConstantSymbol("CAMERA_BEHINDNESS_ANGLE", SymbolTable.INT, "8")},
            {"CAMERA_BEHINDNESS_LAG", new ConstantSymbol("CAMERA_BEHINDNESS_LAG", SymbolTable.INT, "9")},
            {"CAMERA_POSITION_THRESHOLD", new ConstantSymbol("CAMERA_POSITION_THRESHOLD", SymbolTable.INT, "10")},
            {"CAMERA_FOCUS_THRESHOLD", new ConstantSymbol("CAMERA_FOCUS_THRESHOLD", SymbolTable.INT, "11")},
            {"CAMERA_ACTIVE", new ConstantSymbol("CAMERA_ACTIVE", SymbolTable.INT, "12")},
            {"CAMERA_POSITION", new ConstantSymbol("CAMERA_POSITION", SymbolTable.INT, "13")},
            {"CAMERA_POSITION_X", new ConstantSymbol("CAMERA_POSITION_X", SymbolTable.INT, "14")},
            {"CAMERA_POSITION_Y", new ConstantSymbol("CAMERA_POSITION_Y", SymbolTable.INT, "15")},
            {"CAMERA_POSITION_Z", new ConstantSymbol("CAMERA_POSITION_Z", SymbolTable.INT, "16")},
            {"CAMERA_FOCUS", new ConstantSymbol("CAMERA_FOCUS", SymbolTable.INT, "17")},
            {"CAMERA_FOCUS_X", new ConstantSymbol("CAMERA_FOCUS_X", SymbolTable.INT, "18")},
            {"CAMERA_FOCUS_Y", new ConstantSymbol("CAMERA_FOCUS_Y", SymbolTable.INT, "19")},
            {"CAMERA_FOCUS_Z", new ConstantSymbol("CAMERA_FOCUS_Z", SymbolTable.INT, "20")},
            {"CAMERA_POSITION_LOCKED", new ConstantSymbol("CAMERA_POSITION_LOCKED", SymbolTable.INT, "21")},
            {"CAMERA_FOCUS_LOCKED", new ConstantSymbol("CAMERA_FOCUS_LOCKED", SymbolTable.INT, "22")},
            {"PARCEL_DETAILS_NAME", new ConstantSymbol("PARCEL_DETAILS_NAME", SymbolTable.INT, "0")},
            {"PARCEL_DETAILS_DESC", new ConstantSymbol("PARCEL_DETAILS_DESC", SymbolTable.INT, "1")},
            {"PARCEL_DETAILS_OWNER", new ConstantSymbol("PARCEL_DETAILS_OWNER", SymbolTable.INT, "2")},
            {"PARCEL_DETAILS_GROUP", new ConstantSymbol("PARCEL_DETAILS_GROUP", SymbolTable.INT, "3")},
            {"PARCEL_DETAILS_AREA", new ConstantSymbol("PARCEL_DETAILS_AREA", SymbolTable.INT, "4")},
            {"PARCEL_DETAILS_ID", new ConstantSymbol("PARCEL_DETAILS_ID", SymbolTable.INT, "5")},
            {"PARCEL_DETAILS_SEE_AVATARS", new ConstantSymbol("PARCEL_DETAILS_SEE_AVATARS", SymbolTable.INT, "6")},
            {"CLICK_ACTION_NONE", new ConstantSymbol("CLICK_ACTION_NONE", SymbolTable.INT, "0")},
            {"CLICK_ACTION_TOUCH", new ConstantSymbol("CLICK_ACTION_TOUCH", SymbolTable.INT, "0")},
            {"CLICK_ACTION_SIT", new ConstantSymbol("CLICK_ACTION_SIT", SymbolTable.INT, "1")},
            {"CLICK_ACTION_BUY", new ConstantSymbol("CLICK_ACTION_BUY", SymbolTable.INT, "2")},
            {"CLICK_ACTION_PAY", new ConstantSymbol("CLICK_ACTION_PAY", SymbolTable.INT, "3")},
            {"CLICK_ACTION_OPEN", new ConstantSymbol("CLICK_ACTION_OPEN", SymbolTable.INT, "4")},
            {"CLICK_ACTION_PLAY", new ConstantSymbol("CLICK_ACTION_PLAY", SymbolTable.INT, "5")},
            {"CLICK_ACTION_OPEN_MEDIA", new ConstantSymbol("CLICK_ACTION_OPEN_MEDIA", SymbolTable.INT, "6")},
            {"CLICK_ACTION_ZOOM", new ConstantSymbol("CLICK_ACTION_ZOOM", SymbolTable.INT, "7")},
            {"TEXTURE_BLANK", new ConstantSymbol("TEXTURE_BLANK", SymbolTable.KEY, "5748decc-f629-461c-9a36-a35a221fe21f")},
            {"TEXTURE_DEFAULT", new ConstantSymbol("TEXTURE_DEFAULT", SymbolTable.KEY, "89556747-24cb-43ed-920b-47caed15465f")},
            {"TEXTURE_PLYWOOD", new ConstantSymbol("TEXTURE_PLYWOOD", SymbolTable.KEY, "89556747-24cb-43ed-920b-47caed15465f")},
            {"TEXTURE_TRANSPARENT", new ConstantSymbol("TEXTURE_TRANSPARENT", SymbolTable.KEY, "8dcd4a48-2d37-4909-9f78-f7a9eb4ef903")},
            {"TEXTURE_MEDIA", new ConstantSymbol("TEXTURE_MEDIA", SymbolTable.KEY, "8b5fec65-8d8d-9dc5-cda8-8fdf2716e361")},
            {"URL_REQUEST_GRANTED", new ConstantSymbol("URL_REQUEST_GRANTED", SymbolTable.STRING, "URL_REQUEST_GRANTED")},
            {"URL_REQUEST_DENIED", new ConstantSymbol("URL_REQUEST_DENIED", SymbolTable.STRING, "URL_REQUEST_DENIED")},

            {"STATUS_OK", new ConstantSymbol("STATUS_OK", SymbolTable.INT, "0")},
            {"STATUS_MALFORMED_PARAMS", new ConstantSymbol("STATUS_MALFORMED_PARAMS", SymbolTable.INT, "1000")},
            {"STATUS_TYPE_MISMATCH", new ConstantSymbol("STATUS_TYPE_MISMATCH", SymbolTable.INT, "1001")},
            {"STATUS_BOUNDS_ERROR", new ConstantSymbol("STATUS_BOUNDS_ERROR", SymbolTable.INT, "1002")},
            {"STATUS_NOT_FOUND", new ConstantSymbol("STATUS_NOT_FOUND", SymbolTable.INT, "1003")},
            {"STATUS_NOT_SUPPORTED", new ConstantSymbol("STATUS_NOT_SUPPORTED", SymbolTable.INT, "1004")},
            {"STATUS_INTERNAL_ERROR", new ConstantSymbol("STATUS_INTERNAL_ERROR", SymbolTable.INT, "1999")},
            {"STATUS_WHITELIST_FAILED", new ConstantSymbol("STATUS_WHITELIST_FAILED", SymbolTable.INT, "2001")},
            {"PRIM_MEDIA_PERM_NONE", new ConstantSymbol("PRIM_MEDIA_PERM_NONE", SymbolTable.INT, "0")},
            {"PRIM_MEDIA_PERM_OWNER", new ConstantSymbol("PRIM_MEDIA_PERM_OWNER", SymbolTable.INT, "1")},
            {"PRIM_MEDIA_PERM_GROUP", new ConstantSymbol("PRIM_MEDIA_PERM_GROUP", SymbolTable.INT, "2")},
            {"PRIM_MEDIA_PERM_ANYONE", new ConstantSymbol("PRIM_MEDIA_PERM_ANYONE", SymbolTable.INT, "4")},

            {"PRIM_MEDIA_ALT_IMAGE_ENABLE", new ConstantSymbol("PRIM_MEDIA_ALT_IMAGE_ENABLE", SymbolTable.INT, "0")},
            {"PRIM_MEDIA_CONTROLS", new ConstantSymbol("PRIM_MEDIA_CONTROLS", SymbolTable.INT, "1")},
            {"PRIM_MEDIA_CURRENT_URL", new ConstantSymbol("PRIM_MEDIA_CURRENT_URL", SymbolTable.INT, "2")},
            {"PRIM_MEDIA_HOME_URL", new ConstantSymbol("PRIM_MEDIA_HOME_URL", SymbolTable.INT, "3")},
            {"PRIM_MEDIA_AUTO_LOOP", new ConstantSymbol("PRIM_MEDIA_AUTO_LOOP", SymbolTable.INT, "4")},
            {"PRIM_MEDIA_AUTO_PLAY", new ConstantSymbol("PRIM_MEDIA_AUTO_PLAY", SymbolTable.INT, "5")},
            {"PRIM_MEDIA_AUTO_SCALE", new ConstantSymbol("PRIM_MEDIA_AUTO_SCALE", SymbolTable.INT, "6")},
            {"PRIM_MEDIA_AUTO_ZOOM", new ConstantSymbol("PRIM_MEDIA_AUTO_ZOOM", SymbolTable.INT, "7")},
            {"PRIM_MEDIA_FIRST_CLICK_INTERACT", new ConstantSymbol("PRIM_MEDIA_FIRST_CLICK_INTERACT", SymbolTable.INT, "8")},
            {"PRIM_MEDIA_WIDTH_PIXELS", new ConstantSymbol("PRIM_MEDIA_WIDTH_PIXELS", SymbolTable.INT, "9")},
            {"PRIM_MEDIA_HEIGHT_PIXELS", new ConstantSymbol("PRIM_MEDIA_HEIGHT_PIXELS", SymbolTable.INT, "10")},
            {"PRIM_MEDIA_WHITELIST_ENABLE", new ConstantSymbol("PRIM_MEDIA_WHITELIST_ENABLE", SymbolTable.INT, "11")},
            {"PRIM_MEDIA_WHITELIST", new ConstantSymbol("PRIM_MEDIA_WHITELIST", SymbolTable.INT, "12")},
            {"PRIM_MEDIA_PERMS_INTERACT", new ConstantSymbol("PRIM_MEDIA_PERMS_INTERACT", SymbolTable.INT, "13")},
            {"PRIM_MEDIA_PERMS_CONTROL", new ConstantSymbol("PRIM_MEDIA_PERMS_CONTROL", SymbolTable.INT, "14")},

            {"PRIM_MEDIA_CONTROLS_STANDARD", new ConstantSymbol("PRIM_MEDIA_CONTROLS_STANDARD", SymbolTable.INT, "0")},
            {"PRIM_MEDIA_CONTROLS_MINI", new ConstantSymbol("PRIM_MEDIA_CONTROLS_MINI", SymbolTable.INT, "1")},

            {"DENSITY", new ConstantSymbol("DENSITY", SymbolTable.INT, "1")},
            {"FRICTION", new ConstantSymbol("FRICTION", SymbolTable.INT, "2")},
            {"RESTITUTION", new ConstantSymbol("RESTITUTION", SymbolTable.INT, "4")},
            {"GRAVITY_MULTIPLIER", new ConstantSymbol("GRAVITY_MULTIPLIER", SymbolTable.INT, "8")},

            {"AGENT_LIST_PARCEL", new ConstantSymbol("AGENT_LIST_PARCEL", SymbolTable.INT, "1")},
            {"AGENT_LIST_PARCEL_OWNER", new ConstantSymbol("AGENT_LIST_PARCEL_OWNER", SymbolTable.INT, "2")},
            {"AGENT_LIST_REGION", new ConstantSymbol("AGENT_LIST_REGION", SymbolTable.INT, "4")},

            {"ESTATE_ACCESS_ALLOWED_AGENT_ADD", new ConstantSymbol("ESTATE_ACCESS_ALLOWED_AGENT_ADD", SymbolTable.INT, "0")},
            {"ESTATE_ACCESS_ALLOWED_AGENT_REMOVE", new ConstantSymbol("ESTATE_ACCESS_ALLOWED_AGENT_REMOVE", SymbolTable.INT, "1")},
            {"ESTATE_ACCESS_ALLOWED_GROUP_ADD", new ConstantSymbol("ESTATE_ACCESS_ALLOWED_GROUP_ADD", SymbolTable.INT, "2")},
            {"ESTATE_ACCESS_ALLOWED_GROUP_REMOVE", new ConstantSymbol("ESTATE_ACCESS_ALLOWED_GROUP_REMOVE", SymbolTable.INT, "3")},
            {"ESTATE_ACCESS_BANNED_AGENT_ADD", new ConstantSymbol("ESTATE_ACCESS_BANNED_AGENT_ADD", SymbolTable.INT, "4")},
            {"ESTATE_ACCESS_BANNED_AGENT_REMOVE", new ConstantSymbol("ESTATE_ACCESS_BANNED_AGENT_REMOVE", SymbolTable.INT, "5")},
            {"ESTATE_ACCESS_QUERY_CAN_MANAGE", new ConstantSymbol("ESTATE_ACCESS_QUERY_CAN_MANAGE", SymbolTable.INT, "11000")},
            {"ESTATE_ACCESS_QUERY_ALLOWED_AGENT", new ConstantSymbol("ESTATE_ACCESS_QUERY_ALLOWED_AGENT", SymbolTable.INT, "11001")},
            {"ESTATE_ACCESS_QUERY_ALLOWED_GROUP", new ConstantSymbol("ESTATE_ACCESS_QUERY_ALLOWED_GROUP", SymbolTable.INT, "11002")},
            {"ESTATE_ACCESS_QUERY_BANNED_AGENT", new ConstantSymbol("ESTATE_ACCESS_QUERY_BANNED_AGENT", SymbolTable.INT, "11003")},


            {"WIND_SPEED_DEFAULT", new ConstantSymbol("WIND_SPEED_DEFAULT", SymbolTable.INT, "0")},
            {"WIND_SPEED_FIXED", new ConstantSymbol("WIND_SPEED_FIXED", SymbolTable.INT, "1")},
            {"WIND_SPEED_TERRAIN_TURBULENCE", new ConstantSymbol("WIND_SPEED_TERRAIN_TURBULENCE", SymbolTable.INT, "2")},

            {"IW_POWER_INVITE", new ConstantSymbol("IW_POWER_INVITE", SymbolTable.INT, "2")},
            {"IW_POWER_EJECT", new ConstantSymbol("IW_POWER_EJECT", SymbolTable.INT, "4") },
            {"IW_POWER_GROUP_OPTIONS", new ConstantSymbol("IW_POWER_GROUP_OPTIONS", SymbolTable.INT, "8")},
            {"IW_POWER_CREATE_ROLE", new ConstantSymbol("IW_POWER_CREATE_ROLE", SymbolTable.INT, "16")},
            {"IW_POWER_DELETE_ROLE", new ConstantSymbol("IW_POWER_DELETE_ROLE", SymbolTable.INT, "32")},
            {"IW_POWER_ROLE_PROPERTIES", new ConstantSymbol("IW_POWER_ROLE_PROPERTIES", SymbolTable.INT, "64")},
            {"IW_POWER_ASSIGN_LIMITED", new ConstantSymbol("IW_POWER_ASSIGN_LIMITED", SymbolTable.INT, "128")},
            {"IW_POWER_ASSIGN_ANY", new ConstantSymbol("IW_POWER_ASSIGN_ANY", SymbolTable.INT, "256")},
            {"IW_POWER_REMOVE_ANY", new ConstantSymbol("IW_POWER_REMOVE_ANY", SymbolTable.INT, "512")},
            {"IW_POWER_CHANGE_ABILITIES", new ConstantSymbol("IW_POWER_CHANGE_ABILITIES", SymbolTable.INT, "1024")},
            {"IW_POWER_GROUP_IDENTITY", new ConstantSymbol("IW_POWER_GROUP_IDENTITY", SymbolTable.INT, "2048")},
            {"IW_POWER_LAND_DEED", new ConstantSymbol("IW_POWER_LAND_DEED", SymbolTable.INT, "4096")},
            {"IW_POWER_LAND_RELEASE", new ConstantSymbol("IW_POWER_LAND_RELEASE", SymbolTable.INT, "8192")},
            {"IW_POWER_LAND_SALE", new ConstantSymbol("IW_POWER_LAND_SALE", SymbolTable.INT, "16384")},
            {"IW_POWER_LAND_JOIN", new ConstantSymbol("IW_POWER_LAND_JOIN", SymbolTable.INT, "32768")},
            {"IW_POWER_CHAT_JOIN", new ConstantSymbol("IW_POWER_CHAT_JOIN", SymbolTable.INT, "65536")},
            {"IW_POWER_FIND_PLACES", new ConstantSymbol("IW_POWER_FIND_PLACES", SymbolTable.INT, "131072")},
            {"IW_POWER_LAND_IDENTITY", new ConstantSymbol("IW_POWER_LAND_IDENTITY", SymbolTable.INT, "262144")},
            {"IW_POWER_LANDING_POINT", new ConstantSymbol("IW_POWER_LANDING_POINT", SymbolTable.INT, "524288")},
            {"IW_POWER_CHANGE_MEDIA", new ConstantSymbol("IW_POWER_CHANGE_MEDIA", SymbolTable.INT, "1048576")},
            {"IW_POWER_TERRAIN_OPTION", new ConstantSymbol("IW_POWER_TERRAIN_OPTION", SymbolTable.INT, "2097152")},
            {"IW_POWER_LAND_OPTIONS", new ConstantSymbol("IW_POWER_LAND_OPTIONS", SymbolTable.INT, "4194304")},
            {"IW_POWER_ALLOW_TERRAIN", new ConstantSymbol("IW_POWER_ALLOW_TERRAIN", SymbolTable.INT, "8388608")},
            {"IW_POWER_ALLOW_FLY", new ConstantSymbol("IW_POWER_ALLOW_FLY", SymbolTable.INT, "16777216")},
            {"IW_POWER_ALLOW_REZ", new ConstantSymbol("IW_POWER_ALLOW_REZ", SymbolTable.INT, "33554432")},
            {"IW_POWER_ALLOW_LANDMARK", new ConstantSymbol("IW_POWER_ALLOW_LANDMARK", SymbolTable.INT, "67108864")},
            {"IW_POWER_ALLOW_VOICE", new ConstantSymbol("IW_POWER_ALLOW_VOICE", SymbolTable.INT, "134217728")},
            {"IW_POWER_ALLOW_HOME", new ConstantSymbol("IW_POWER_ALLOW_HOME", SymbolTable.INT, "268435456")},
            {"IW_POWER_MANAGE_LAND", new ConstantSymbol("IW_POWER_MANAGE_LAND", SymbolTable.INT, "536870912")},
            {"IW_POWER_MANAGE_BANNED", new ConstantSymbol("IW_POWER_MANAGE_BANNED", SymbolTable.INT, "1073741824")},
            {"IW_POWER_MANAGE_PASSES", new ConstantSymbol("IW_POWER_MANAGE_PASSES", SymbolTable.INT, "2147483648")},
            {"IW_POWER_FREEZE_EJECT", new ConstantSymbol("IW_POWER_FREEZE_EJECT", SymbolTable.INT, "4294967296")},
            {"IW_POWER_RETURN_GROUP", new ConstantSymbol("IW_POWER_RETURN_GROUP", SymbolTable.INT, "8589934592")},
            {"IW_POWER_RETURN_NONGROUP", new ConstantSymbol("IW_POWER_RETURN_NONGROUP", SymbolTable.INT, "17179869184")},
            {"IW_POWER_LANDSCAPE_PLANTS", new ConstantSymbol("IW_POWER_LANDSCAPE_PLANTS", SymbolTable.INT, "34359738368")},
            {"IW_POWER_OBJECT_DEED", new ConstantSymbol("IW_POWER_OBJECT_DEED", SymbolTable.INT, "68719476736")},
            {"IW_POWER_CHAT_MODERATE", new ConstantSymbol("IW_POWER_CHAT_MODERATE", SymbolTable.INT, "137438953472")},
            {"IW_POWER_OBJECT_MOVE", new ConstantSymbol("IW_POWER_OBJECT_MOVE", SymbolTable.INT, "274877906944")},
            {"IW_POWER_OBJECT_SALE", new ConstantSymbol("IW_POWER_OBJECT_SALE", SymbolTable.INT, "549755813888")},
            {"IW_POWER_ACCOUNTABLE", new ConstantSymbol("IW_POWER_ACCOUNTABLE", SymbolTable.INT, "1099511627776")},
            {"IW_POWER_HOST_EVENT", new ConstantSymbol("IW_POWER_HOST_EVENT", SymbolTable.INT, "2199023255552")},
            {"IW_POWER_NOTICE_SEND", new ConstantSymbol("IW_POWER_NOTICE_SEND", SymbolTable.INT, "4398046511104")},
            {"IW_POWER_NOTICE_RECV", new ConstantSymbol("IW_POWER_NOTICE_RECV", SymbolTable.INT, "8796093022208")},
            {"IW_POWER_PROPOSAL_ADD", new ConstantSymbol("IW_POWER_PROPOSAL_ADD", SymbolTable.INT, "17592186044416")},
            {"IW_POWER_PROPOSAL_VOTE", new ConstantSymbol("IW_POWER_PROPOSAL_VOTE", SymbolTable.INT, "35184372088832")},
            {"IW_POWER_VISIBLE", new ConstantSymbol("IW_POWER_VISIBLE", SymbolTable.INT, "140737488355328")},
            {"IW_POWER_OBJECT_RETURN", new ConstantSymbol("IW_POWER_OBJECT_RETURN", SymbolTable.INT, "281474976710656")},

            // Values for llCastRay
            {"RC_REJECT_TYPES", new ConstantSymbol("RC_REJECT_TYPES", SymbolTable.INT, "0")},
            {"RC_DETECT_PHANTOM", new ConstantSymbol("RC_DETECT_PHANTOM", SymbolTable.INT, "1")},
            {"RC_DATA_FLAGS", new ConstantSymbol("RC_DATA_FLAGS", SymbolTable.INT, "2")},
            {"RC_MAX_HITS", new ConstantSymbol("RC_MAX_HITS", SymbolTable.INT, "3")},
            // Values for RC_REJECT_TYPES
            {"RC_REJECT_AGENTS", new ConstantSymbol("RC_REJECT_AGENTS", SymbolTable.INT, "1")},
            {"RC_REJECT_PHYSICAL", new ConstantSymbol("RC_REJECT_PHYSICAL", SymbolTable.INT, "2")},
            {"RC_REJECT_NONPHYSICAL", new ConstantSymbol("RC_REJECT_NONPHYSICAL", SymbolTable.INT, "4")},
            {"RC_REJECT_LAND", new ConstantSymbol("RC_REJECT_LAND", SymbolTable.INT, "8")},
            // Values for RC_DATA_FLAGS
            {"RC_GET_NORMAL", new ConstantSymbol("RC_GET_NORMAL", SymbolTable.INT, "1")},
            {"RC_GET_ROOT_KEY", new ConstantSymbol("RC_GET_ROOT_KEY", SymbolTable.INT, "2")},
            {"RC_GET_LINK_NUM", new ConstantSymbol("RC_GET_LINK_NUM", SymbolTable.INT, "4")},
            // Return values from llCastRay
            {"RCERR_UNKNOWN", new ConstantSymbol("RCERR_UNKNOWN", SymbolTable.INT, "-1")},
            {"RCERR_SIM_PERF_LOW", new ConstantSymbol("RCERR_SIM_PERF_LOW", SymbolTable.INT, "-2")},
            {"RCERR_CAST_TIME_EXCEEDED", new ConstantSymbol("RCERR_CAST_TIME_EXCEEDED", SymbolTable.INT, "-3")},
            
            //Values for llSetKeyframedMotion
            {"KFM_COMMAND", new ConstantSymbol("KFM_COMMAND", SymbolTable.INT, "0")},
            {"KFM_MODE", new ConstantSymbol("KFM_MODE", SymbolTable.INT, "1")},
            {"KFM_DATA", new ConstantSymbol("KFM_DATA", SymbolTable.INT, "2")},
            //Values for KFM_COMMAND
            {"KFM_CMD_PLAY", new ConstantSymbol("KFM_CMD_PLAY", SymbolTable.INT, "0")},
            {"KFM_CMD_STOP", new ConstantSymbol("KFM_CMD_STOP", SymbolTable.INT, "1")},
            {"KFM_CMD_PAUSE", new ConstantSymbol("KFM_CMD_PAUSE", SymbolTable.INT, "2")},
            //Values for KFM_MODE
            {"KFM_FORWARD", new ConstantSymbol("KFM_FORWARD", SymbolTable.INT, "0")},
            {"KFM_LOOP", new ConstantSymbol("KFM_LOOP", SymbolTable.INT, "1")},
            {"KFM_PING_PONG", new ConstantSymbol("KFM_PING_PONG", SymbolTable.INT, "2")},
            {"KFM_REVERSE", new ConstantSymbol("KFM_REVERSE", SymbolTable.INT, "3")},
            //Values for KFM_DATA
            {"KFM_ROTATION", new ConstantSymbol("KFM_ROTATION", SymbolTable.INT, "1")},
            {"KFM_TRANSLATION", new ConstantSymbol("KFM_TRANSLATION", SymbolTable.INT, "2")},

            //Values for bot functions
            {"BOT_ERROR", new ConstantSymbol("BOT_ERROR", SymbolTable.INT, "-3")},
            {"BOT_USER_NOT_FOUND", new ConstantSymbol("BOT_USER_NOT_FOUND", SymbolTable.INT, "-2")},
            {"BOT_NOT_FOUND", new ConstantSymbol("BOT_NOT_FOUND", SymbolTable.INT, "-1")},
            {"BOT_SUCCESS", new ConstantSymbol("BOT_SUCCESS", SymbolTable.INT, "0")},
            
            {"BOT_ALLOW_RUNNING", new ConstantSymbol("BOT_ALLOW_RUNNING", SymbolTable.INT, "1")},
            {"BOT_ALLOW_FLYING", new ConstantSymbol("BOT_ALLOW_FLYING", SymbolTable.INT, "2")},
            {"BOT_ALLOW_JUMPING", new ConstantSymbol("BOT_ALLOW_JUMPING", SymbolTable.INT, "3")},
            {"BOT_FOLLOW_OFFSET", new ConstantSymbol("BOT_FOLLOW_OFFSET", SymbolTable.INT, "4")},
            {"BOT_REQUIRES_LINE_OF_SIGHT", new ConstantSymbol("BOT_REQUIRES_LINE_OF_SIGHT", SymbolTable.INT, "5")},
            {"BOT_START_FOLLOWING_DISTANCE", new ConstantSymbol("BOT_START_FOLLOWING_DISTANCE", SymbolTable.INT, "6")},
            {"BOT_STOP_FOLLOWING_DISTANCE", new ConstantSymbol("BOT_STOP_FOLLOWING_DISTANCE", SymbolTable.INT, "7")},
            {"BOT_LOST_AVATAR_DISTANCE", new ConstantSymbol("BOT_LOST_AVATAR_DISTANCE", SymbolTable.INT, "8")},
            
            {"BOT_TRAVELMODE_WALK", new ConstantSymbol("BOT_TRAVELMODE_WALK", SymbolTable.INT, "1")},
            {"BOT_TRAVELMODE_RUN", new ConstantSymbol("BOT_TRAVELMODE_RUN", SymbolTable.INT, "2")},
            {"BOT_TRAVELMODE_FLY", new ConstantSymbol("BOT_TRAVELMODE_FLY", SymbolTable.INT, "3")},
            {"BOT_TRAVELMODE_TELEPORT", new ConstantSymbol("BOT_TRAVELMODE_TELEPORT", SymbolTable.INT, "4")},
            {"BOT_TRAVELMODE_WAIT", new ConstantSymbol("BOT_TRAVELMODE_WAIT", SymbolTable.INT, "5")},
            
            {"BOT_MOVEMENT_TYPE", new ConstantSymbol("BOT_MOVEMENT_TYPE", SymbolTable.INT, "0")},
            {"BOT_MOVEMENT_TELEPORT_AFTER", new ConstantSymbol("BOT_MOVEMENT_TELEPORT_AFTER", SymbolTable.INT, "1")},
            
            {"BOT_MOVEMENT_FLAG_NONE", new ConstantSymbol("BOT_MOVEMENT_FLAG_NONE", SymbolTable.INT, "0")},
            {"BOT_MOVEMENT_FLAG_FOLLOW_INDEFINITELY", new ConstantSymbol("BOT_MOVEMENT_FLAG_FOLLOW_INDEFINITELY", SymbolTable.INT, "1")},

            {"BOT_CREATE_DEFAULT", new ConstantSymbol("BOT_CREATE_DEFAULT", SymbolTable.INT, "0")},
            
            {"BOT_MOVE_COMPLETE", new ConstantSymbol("BOT_MOVE_COMPLETE", SymbolTable.INT, "1")},
            {"BOT_MOVE_UPDATE", new ConstantSymbol("BOT_MOVE_UPDATE", SymbolTable.INT, "2")},
            {"BOT_MOVE_FAILED", new ConstantSymbol("BOT_MOVE_FAILED", SymbolTable.INT, "3")},
            {"BOT_MOVE_AVATAR_LOST", new ConstantSymbol("BOT_MOVE_AVATAR_LOST", SymbolTable.INT, "4")},
            
            {"BOT_WANDER_MOVEMENT_TYPE", new ConstantSymbol("BOT_WANDER_MOVEMENT_TYPE", SymbolTable.INT, "1")},
            {"BOT_WANDER_TIME_BETWEEN_NODES", new ConstantSymbol("BOT_WANDER_TIME_BETWEEN_NODES", SymbolTable.INT, "2")},
            
            {"BOT_ABOUT_TEXT", new ConstantSymbol("BOT_ABOUT_TEXT", SymbolTable.INT, "1")},
            {"BOT_EMAIL", new ConstantSymbol("BOT_EMAIL", SymbolTable.INT, "2")},
            {"BOT_IMAGE_UUID", new ConstantSymbol("BOT_IMAGE_UUID", SymbolTable.INT, "3")},
            {"BOT_PROFILE_URL", new ConstantSymbol("BOT_PROFILE_URL", SymbolTable.INT, "4")},

            {"IW_REZ_OK", new ConstantSymbol("IW_REZ_OK", SymbolTable.INT, "0")},
            {"IW_REZ_NOT_PERMITTED", new ConstantSymbol("IW_REZ_NOT_PERMITTED", SymbolTable.INT, "1")},
            {"IW_REZ_REGION_SCENIC", new ConstantSymbol("IW_REZ_REGION_SCENIC", SymbolTable.INT, "2")},
            {"IW_REZ_NO_LAND_PARCEL", new ConstantSymbol("IW_REZ_NO_LAND_PARCEL", SymbolTable.INT, "3")},
            {"IW_REZ_PARCEL_LAND_IMPACT", new ConstantSymbol("IW_REZ_PARCEL_LAND_IMPACT", SymbolTable.INT, "4")},
            {"IW_REZ_REGION_LAND_IMPACT", new ConstantSymbol("IW_REZ_REGION_LAND_IMPACT", SymbolTable.INT, "5")},

            {"IW_APPEARANCE_GENDER", new ConstantSymbol("IW_APPEARANCE_GENDER", SymbolTable.INT, "31")},

            {"IW_MATCH_INCLUDE", new ConstantSymbol("IW_MATCH_INCLUDE", SymbolTable.INT, "-2")},
            {"IW_MATCH_EQUAL", new ConstantSymbol("IW_MATCH_EQUAL", SymbolTable.INT, "-1")},
            {"IW_MATCH_HEAD", new ConstantSymbol("IW_MATCH_HEAD", SymbolTable.INT, "0")},
            {"IW_MATCH_TAIL", new ConstantSymbol("IW_MATCH_TAIL", SymbolTable.INT, "1")},
            {"IW_MATCH_REGEX", new ConstantSymbol("IW_MATCH_REGEX", SymbolTable.INT, "2")},
            {"IW_MATCH_COUNT", new ConstantSymbol("IW_MATCH_COUNT", SymbolTable.INT, "3")},
            {"IW_MATCH_COUNT_REGEX", new ConstantSymbol("IW_MATCH_COUNT_REGEX", SymbolTable.INT, "4")},

            {"IW_COLORSPACE_RGB", new ConstantSymbol("IW_COLORSPACE_RGB", SymbolTable.INT, "0")},
            {"IW_COLORSPACE_HSL", new ConstantSymbol("IW_COLORSPACE_HSL", SymbolTable.INT, "1")},
            {"IW_COLORSPACE_HSV", new ConstantSymbol("IW_COLORSPACE_HSV", SymbolTable.INT, "2")},

            // Generic operations result codes that can be used to provide a unified number space for operation return codes. 
                // 0: ok/success (two aliases that may be more appealing depending on your preferences)
            { "IW_SUCCESS", new ConstantSymbol("IW_SUCCESS", SymbolTable.INT, "0") }, 
            { "IWERR_NONE", new ConstantSymbol("IWERR_NONE", SymbolTable.INT, "0") }, 
                // 1: ignored, the request was redundant, nothing needed to be done
            { "IWERR_NOCHANGE", new ConstantSymbol("IWERR_NOCHANGE", SymbolTable.INT, "1") },
                // 2: generic error, internal server failure (like module not loaded)
            { "IWERR_FAILED", new ConstantSymbol("IWERR_FAILED", SymbolTable.INT, "2") },
                // 3: one or more of the parameters is invalid
            { "IWERR_PARAMETER", new ConstantSymbol("IWERR_PARAMETER", SymbolTable.INT, "3") },
                // 4: forbidden, due to region/parcel access restrictions
            { "IWERR_ACCESS", new ConstantSymbol("IWERR_ACCESS", SymbolTable.INT, "4") },
                // 5: forbidden, permissions error or missing group role
            { "IWERR_PERMISSION", new ConstantSymbol("IWERR_PERMISSION", SymbolTable.INT, "5") },
                // 6: operations prevented due to muting
            { "IWERR_MUTED", new ConstantSymbol("IWERR_MUTED", SymbolTable.INT, "6") },
                // 7: the ID/target/object does not exist
            { "IWERR_NOTFOUND", new ConstantSymbol("IWERR_NOTFOUND", SymbolTable.INT, "7") },

			// Return codes for iwRemoteLoadScriptPin
			{ "IW_REMOTELOAD_SUCCESS", new ConstantSymbol("IW_REMOTELOAD_SUCCESS", SymbolTable.INT,  "1") },
			{ "IW_REMOTELOAD_FAILURE", new ConstantSymbol("IW_REMOTELOAD_FAILURE", SymbolTable.INT,  "0") },
			{ "IW_REMOTELOAD_BAD_PIN", new ConstantSymbol("IW_REMOTELOAD_BAD_PIN", SymbolTable.INT, "-1") },
			{ "IW_REMOTELOAD_NO_PIN",  new ConstantSymbol("IW_REMOTELOAD_NO_PIN",  SymbolTable.INT, "-2") },

			// Return codes for iwDeliverInventory and iwDeliverInventoryList
			{ "IW_DELIVER_OK",      new ConstantSymbol("IW_DELIVER_OK",     SymbolTable.INT, "0") },
			{ "IW_DELIVER_BADKEY",  new ConstantSymbol("IW_DELIVER_BADKEY", SymbolTable.INT, "1") },
			{ "IW_DELIVER_MUTED",   new ConstantSymbol("IW_DELIVER_MUTED",  SymbolTable.INT, "2") },
			{ "IW_DELIVER_ITEM",    new ConstantSymbol("IW_DELIVER_ITEM",   SymbolTable.INT, "3") },
			{ "IW_DELIVER_PRIM",    new ConstantSymbol("IW_DELIVER_PRIM",   SymbolTable.INT, "4") },
			{ "IW_DELIVER_USER",    new ConstantSymbol("IW_DELIVER_USER",   SymbolTable.INT, "5") },
			{ "IW_DELIVER_PERM",    new ConstantSymbol("IW_DELIVER_PERM",   SymbolTable.INT, "6") },
			{ "IW_DELIVER_NONE",    new ConstantSymbol("IW_DELIVER_NONE",   SymbolTable.INT, "7") },
        };
    }
}
